//https://github.com/pret/pokered/blob/6b5be9129cabe72b9f775b02db1bf7e7169153da/data/moves/animations.asm
const char *Animations[]=
{
    "000 - 0x00 INVALID", //move table starts with pound but pound is move 01 not 00"
    "001 - PoundAnim",
    "002 - KarateChopAnim",
    "003 - DoubleSlapAnim",
    "004 - CometPunchAnim",
    "005 - MegaPunchAnim",
    "006 - PayDayAnim",
    "007 - FirePunchAnim",
    "008 - IcePunchAnim",
    "009 - ThunderPunchAnim",
    "010 - ScratchAnim",
    "011 - VicegripAnim",
    "012 - GuillotineAnim",
    "013 - RazorWindAnim",
    "014 - SwordsDanceAnim",
    "015 - CutAnim",
    "016 - GustAnim",
    "017 - WingAttackAnim",
    "018 - WhirlwindAnim",
    "019 - FlyAnim",
    "020 - BindAnim",
    "021 - SlamAnim",
    "022 - VineWhipAnim",
    "023 - StompAnim",
    "024 - DoubleKickAnim",
    "025 - MegaKickAnim",
    "026 - JumpKickAnim",
    "027 - RollingKickAnim",
    "028 - SandAttackAnim",
    "029 - HeatButtAnim",
    "030 - HornAttackAnim",
    "031 - FuryAttackAnim",
    "032 - HornDrillAnim",
    "033 - TackleAnim",
    "034 - BodySlamAnim",
    "035 - WrapAnim",
    "036 - TakeDownAnim",
    "037 - ThrashAnim",
    "038 - DoubleEdgeAnim",
    "039 - TailWhipAnim",
    "040 - PoisonStingAnim",
    "041 - TwineedleAnim",
    "042 - PinMissileAnim",
    "043 - LeerAnim",
    "044 - BiteAnim",
    "045 - GrowlAnim",
    "046 - RoarAnim",
    "047 - SingAnim",
    "048 - SupersonicAnim",
    "049 - SonicBoomAnim",
    "050 - DisableAnim",
    "051 - AcidAnim",
    "052 - EmberAnim",
    "053 - FlamethrowerAnim",
    "054 - MistAnim",
    "055 - WaterGunAnim",
    "056 - HydroPumpAnim",
    "057 - SurfAnim",
    "058 - IceBeamAnim",
    "059 - BlizzardAnim",
    "060 - PsyBeamAnim",
    "061 - BubbleBeamAnim",
    "062 - AuroraBeamAnim",
    "063 - HyperBeamAnim",
    "064 - PeckAnim",
    "065 - DrillPeckAnim",
    "066 - SubmissionAnim",
    "067 - LowKickAnim",
    "068 - CounterAnim",
    "069 - SeismicTossAnim",
    "070 - StrengthAnim",
    "071 - AbsorbAnim",
    "072 - MegaDrainAnim",
    "073 - LeechSeedAnim",
    "074 - GrowthAnim",
    "075 - RazorLeafAnim",
    "076 - SolarBeamAnim",
    "077 - PoisonPowderAnim",
    "078 - StunSporeAnim",
    "079 - SleepPowderAnim",
    "080 - PetalDanceAnim",
    "081 - StringShotAnim",
    "082 - DragonRageAnim",
    "083 - FireSpinAnim",
    "084 - ThunderShockAnim",
    "085 - ThunderBoltAnim",
    "086 - ThunderWaveAnim",
    "087 - ThunderAnim",
    "088 - RockThrowAnim",
    "089 - EarthquakeAnim",
    "090 - FissureAnim",
    "091 - DigAnim",
    "092 - ToxicAnim",
    "093 - ConfusionAnim",
    "094 - PsychicAnim",
    "095 - HypnosisAnim",
    "096 - MeditateAnim",
    "097 - AgilityAnim",
    "098 - QuickAttackAnim",
    "099 - RageAnim",
    "100 - TeleportAnim",
    "101 - NightShadeAnim",
    "102 - MimicAnim",
    "103 - ScreechAnim",
    "104 - DoubleTeamAnim",
    "105 - RecoverAnim",
    "106 - HardenAnim",
    "107 - MinimizeAnim",
    "108 - SmokeScreenAnim",
    "109 - ConfuseRayAnim",
    "110 - WithdrawAnim",
    "111 - DefenseCurlAnim",
    "112 - BarrierAnim",
    "113 - LightScreenAnim",
    "114 - HazeAnim",
    "115 - ReflectAnim",
    "116 - FocusEnergyAnim",
    "117 - BideAnim",
    "118 - MetronomeAnim",
    "119 - MirrorMoveAnim",
    "120 - SelfdestructAnim",
    "121 - EggBombAnim",
    "122 - LickAnim",
    "123 - SmogAnim",
    "124 - SludgeAnim",
    "125 - BoneClubAnim",
    "126 - FireBlastAnim",
    "127 - WaterfallAnim",
    "128 - ClampAnim",
    "129 - SwiftAnim",
    "130 - SkullBashAnim",
    "131 - SpikeCannonAnim",
    "132 - ConstrictAnim",
    "133 - AmnesiaAnim",
    "134 - KinesisAnim",
    "135 - SoftboiledAnim",
    "136 - HiJumpKickAnim",
    "137 - GlareAnim",
    "138 - DreamEaterAnim",
    "139 - PoisonGasAnim",
    "140 - BarrageAnim",
    "141 - LeechLifeAnim",
    "142 - LovelyKissAnim",
    "143 - SkyAttackAnim",
    "144 - TransformAnim",
    "145 - BubbleAnim",
    "146 - DizzyPunchAnim",
    "147 - SporeAnim",
    "148 - FlashAnim",
    "149 - PsywaveAnim",
    "150 - SplashAnim",
    "151 - AcidArmorAnim",
    "152 - CrabHammerAnim",
    "153 - ExplosionAnim",
    "154 - FurySwipesAnim",
    "155 - BonemerangAnim",
    "156 - RestAnim",
    "157 - RockSlideAnim",
    "158 - HyperFangAnim",
    "159 - SharpenAnim",
    "160 - ConversionAnim",
    "161 - TriAttackAnim",
    "162 - SuperFangAnim",
    "163 - SlashAnim",
    "164 - SubstituteAnim",
    "165 - StruggleAnim",
    //Move Animations end here
    "166 - ShowPicAnim",
    "167 - EnemyFlashAnim",
    "168 - PlayerFlashAnim",
    "169 - EnemyHUDShakeAnim",
    "170 - TradeBallDropAnim",
    "171 - TradeBallAppear1Anim",
    "172 - TradeBallAppear2Anim",
    "173 - TradeBallPoofAnim",
    "174 - XStatItemAnim",
    "175 - XStatItemAnim",
    "176 - ShrinkingSquareAnim",
    "177 - ShrinkingSquareAnim",
    "178 - XStatItemBlackAnim",
    "179 - XStatItemBlackAnim",
    "180 - ShrinkingSquareBlackAnim",
    "181 - ShrinkingSquareBlackAnim",
    "182 - UnusedAnim",
    "183 - UnusedAnim",
    "184 - ParalyzeAnim",
    "185 - ParalyzeAnim",
    "186 - PoisonAnim",
    "187 - PoisonAnim",
    "188 - SleepPlayerAnim",
    "189 - SleepEnemyAnim",
    "190 - ConfusedPlayerAnim",
    "191 - ConfusedEnemyAnim",
    "192 - FaintAnim",
    "193 - BallTossAnim",
    "194 - BallShakeAnim",
    "195 - BallPoofAnim",
    "196 - BallBlockAnim",
    "197 - GreatTossAnim",
    "198 - UltraTossAnim",
    "299 - ShakeScreenAnim",
    "200 - HidePicAnim",
    "201 - ThrowRockAnim",
    "202 - ThrowBaitAnim",
    //Combat animations end here",
    "203 - ZigZagScreenAnim",
    "204 - TripleKickAnim",
    "205 - SacredFireAnim",
    "206 - FeintAttackAnim",
    "207 - ",
    "208 - ",
    "209 - ",
    "210 - ",
    "211 - ",
    "212 - ",
    "213 - ",
    "214 - ",
    "215 - ",
    "216 - ",
    "217 - ",
    "218 - ",
    "219 - ",
    "220 - ",
    "221 - ",
    "222 - ",
    "223 - ",
    "224 - ",
    "225 - ",
    "226 - ",
    "227 - ",
    "228 - ",
    "229 - ",
    "230 - ",
    "231 - ",
    "232 - ",
    "233 - ",
    "234 - ",
    "235 - ",
    "236 - ",
    "237 - ",
    "238 - ",
    "239 - ",
    "240 - ",
    "241 - ",
    "242 - ",
    "243 - ",
    "244 - ",
    "245 - ",
    "246 - ",
    "247 - ",
    "248 - ",
    "249 - ",
    "250 - ",
    "251 - ",
    "252 - ",
    "253 - ",
    "254 - ",
    "255 - ",
    NULL
};

//https://github.com/pret/pokered/blob/6b5be9129cabe72b9f775b02db1bf7e7169153da/constants/move_effect_constants.asm
const char *MoveEffects[]=
{
    "000 - NO_ADDITIONAL_EFFECT",
    "001 - CONFUSION_20P_SIDE_EFFECT (20%) (BROWN)",
    "002 - POISON_SIDE_EFFECT1 (10%)",
    "003 - DRAIN_HP_EFFECT",
    "004 - BURN_SIDE_EFFECT1 (10%)",
    "005 - FREEZE_SIDE_EFFECT (10%)",
    "006 - PARALYZE_SIDE_EFFECT1 (10%)",
    "007 - EXPLODE_EFFECT (Explosion, Self Destruct)",
    "008 - DREAM_EATER_EFFECT",
    "009 - MIRROR_MOVE_EFFECT (SplashEffect on other move IDs)",
    "010 - ATTACK_UP1_EFFECT",
    "011 - DEFENSE_UP1_EFFECT",
    "012 - SPEED_UP1_EFFECT",
    "013 - SPECIAL_UP1_EFFECT",
    "014 - ACCURACY_UP1_EFFECT",
    "015 - EVASION_UP1_EFFECT",
    "016 - PAY_DAY_EFFECT",
    "017 - SWIFT_EFFECT (SplashEffect on other move IDs)",
    "018 - ATTACK_DOWN1_EFFECT",
    "019 - DEFENSE_DOWN1_EFFECT",
    "020 - SPEED_DOWN1_EFFECT",
    "021 - SPECIAL_DOWN1_EFFECT",
    "022 - ACCURACY_DOWN1_EFFECT",
    "023 - EVASION_DOWN1_EFFECT",
    "024 - CONVERSION_EFFECT",
    "025 - HAZE_EFFECT",
    "026 - BIDE_EFFECT",
    "027 - THRASH_PETAL_DANCE_EFFECT",
    "028 - SWITCH_AND_TELEPORT_EFFECT",
    "029 - TWO_TO_FIVE_ATTACKS_EFFECT (random 2-5 attacks)",
    "030 - TRIPLE KICK_EFFECT (always 3 attacks) (BROWN)",
    "031 - FLINCH_SIDE_EFFECT1 (10%)",
    "032 - SLEEP_EFFECT",
    "033 - POISON_SIDE_EFFECT2  (30%)",
    "034 - BURN_SIDE_EFFECT2 (30%)",
    "035 - CONFUSION_SIDE_EFFECT (100%) (DynamicPunch)(BROWN)",
    "036 - PARALYZE_SIDE_EFFECT2 (30%)",
    "037 - FLINCH_SIDE_EFFECT2 (30%)",
    "038 - OHKO_EFFECT (moves like Horn Drill)",
    "039 - CHARGE_EFFECT (moves like Solar Beam)",
    "040 - SUPER_FANG_EFFECT",
    "041 - SPECIAL_DAMAGE_EFFECT (Seismic Toss, Night Shade, Sonic Boom, Dragon Rage, Psywave)",
    "042 - TRAPPING_EFFECT (moves like Wrap)",
    "043 - FLY_EFFECT",
    "044 - ATTACK_TWICE_EFFECT (always 2 attacks)",
    "045 - JUMP_KICK_EFFECT (SplashEffect on other move IDs)",
    "046 - MIST_EFFECT",
    "047 - FOCUS_ENERGY_EFFECT",
    "048 - RECOIL_EFFECT (moves like Double Edge)",
    "049 - CONFUSION_EFFECT (100%) - Status moves",
    "050 - ATTACK_UP2_EFFECT",
    "051 - DEFENSE_UP2_EFFECT",
    "052 - SPEED_UP2_EFFECT",
    "053 - SPECIAL_UP2_EFFECT",
    "054 - ACCURACY_UP2_EFFECT",
    "055 - EVASION_UP2_EFFECT",
    "056 - HEAL_EFFECT (Recover, Softboiled, Rest)",
    "057 - TRANSFORM_EFFECT",
    "058 - ATTACK_DOWN2_EFFECT",
    "059 - DEFENSE_DOWN2_EFFECT",
    "060 - SPEED_DOWN2_EFFECT",
    "061 - SPECIAL_DOWN2_EFFECT",
    "062 - ACCURACY_DOWN2_EFFECT",
    "063 - EVASION_DOWN2_EFFECT",
    "064 - LIGHT_SCREEN_EFFECT",
    "065 - REFLECT_EFFECT",
    "066 - POISON_EFFECT",
    "067 - PARALYZE_EFFECT",
    "068 - ATTACK_DOWN_SIDE_EFFECT",
    "069 - DEFENSE_DOWN_SIDE_EFFECT",
    "070 - SPEED_DOWN_SIDE_EFFECT",
    "071 - SPECIAL_DOWN_SIDE_EFFECT",
    "072 - ACCURACY_DOWN_SIDE_EFFECT (BROWN)",
    "073 - EVASION_DOWN_SIDE_EFFECT (BROWN)",
    "074 - ANCIENTPOWER_EFFECT",
    "075 - TRIATTACK_SIDE_EFFECT3 (BROWN)",
    "076 - CONFUSION_SIDE_EFFECT (10%)",
    "077 - TWINEEDLE_EFFECT (always 2 attacks)",
    "078 - FLINCH_SIDE_EFFECT3 (20%) (BROWN)",
    "079 - SUBSTITUTE_EFFECT",
    "080 - HYPER_BEAM_EFFECT",
    "081 - RAGE_EFFECT",
    "082 - MIMIC_EFFECT",
    "083 - METRONOME_EFFECT",
    "084 - LEECH_SEED_EFFECT",
    "085 - SPLASH_EFFECT",
    "086 - DISABLE_EFFECT",
    "087 - ATTACK_UP1_SIDE_EFFECT (10%) (BROWN)",
    "088 - ATTACK_DOWN1_SIDE_EFFECT (100%)",
    "089 - DICEROLL_EFFECT",
    "090 - ",
    "091 - ",
    "092 - ",
    "093 - ",
    "094 - ",
    "095 - ",
    "096 - ",
    "097 - ",
    "098 - ",
    "099 - ",
    "100 - ",
    "101 - ",
    "102 - ",
    "103 - ",
    "104 - ",
    "105 - ",
    "106 - ",
    "107 - ",
    "108 - ",
    "109 - ",
    "110 - ",
    "111 - ",
    "112 - ",
    "113 - ",
    "114 - ",
    "115 - ",
    "116 - ",
    "117 - ",
    "118 - ",
    "119 - ",
    "120 - ",
    "121 - ",
    "122 - ",
    "123 - ",
    "124 - ",
    "125 - ",
    "126 - ",
    "127 - ",
    "128 - ",
    "129 - ",
    "130 - ",
    "131 - ",
    "132 - ",
    "133 - ",
    "134 - ",
    "135 - ",
    "136 - ",
    "137 - ",
    "138 - ",
    "139 - ",
    "140 - ",
    "141 - ",
    "142 - ",
    "143 - ",
    "144 - ",
    "145 - ",
    "146 - ",
    "147 - ",
    "148 - ",
    "149 - ",
    "150 - ",
    "151 - ",
    "152 - ",
    "153 - ",
    "154 - ",
    "155 - ",
    "156 - ",
    "157 - ",
    "158 - ",
    "159 - ",
    "160 - ",
    "161 - ",
    "162 - ",
    "163 - ",
    "164 - ",
    "165 - ",
    "166 - ",
    "167 - ",
    "168 - ",
    "169 - ",
    "170 - ",
    "171 - ",
    "172 - ",
    "173 - ",
    "174 - ",
    "175 - ",
    "176 - ",
    "177 - ",
    "178 - ",
    "179 - ",
    "180 - ",
    "181 - ",
    "182 - ",
    "183 - ",
    "184 - ",
    "185 - ",
    "186 - ",
    "187 - ",
    "188 - ",
    "189 - ",
    "190 - ",
    "191 - ",
    "192 - ",
    "193 - ",
    "194 - ",
    "195 - ",
    "196 - ",
    "197 - ",
    "198 - ",
    "199 - ",
    "200 - ",
    "201 - ",
    "202 - ",
    "203 - ",
    "204 - ",
    "205 - ",
    "206 - ",
    "207 - ",
    "208 - ",
    "209 - ",
    "210 - ",
    "211 - ",
    "212 - ",
    "213 - ",
    "214 - ",
    "215 - ",
    "216 - ",
    "217 - ",
    "218 - ",
    "219 - ",
    "220 - ",
    "221 - ",
    "222 - ",
    "223 - ",
    "224 - ",
    "225 - ",
    "226 - ",
    "227 - ",
    "228 - ",
    "229 - ",
    "230 - ",
    "231 - ",
    "232 - ",
    "233 - ",
    "234 - ",
    "235 - ",
    "236 - ",
    "237 - ",
    "238 - ",
    "239 - ",
    "240 - ",
    "241 - ",
    "242 - ",
    "243 - ",
    "244 - ",
    "245 - ",
    "246 - ",
    "247 - ",
    "248 - ",
    "249 - ",
    "250 - ",
    "251 - ",
    "252 - ",
    "253 - ",
    "254 - ",
    "255 - ",
    NULL
};

const char *MoveNames[]=
{
    "00_Glitch move",
    "Pound",
    "Karate Chop",
    "Double Slap",
    "Comet Punch",
    "Mega Punch",
    "Pay Day",
    "Fire Punch",
    "Ice Punch",
    "ThunderPunch",
    "Scratch",
    "Vise Grip",
    "Guillotine",
    "Razor Wind",
    "Swords Dance",
    "Cut",
    "Gust",
    "Wing Attack",
    "Whirlwind",
    "Fly",
    "Bind",
    "Slam",
    "Vine Whip",
    "Stomp",
    "Double Kick",
    "Mega Kick",
    "Jump Kick",
    "Rolling Kick",
    "Sand Attack",
    "Headbutt",
    "Horn Attack",
    "Fury Attack",
    "Horn Drill",
    "Tackle",
    "Body Slam",
    "Wrap",
    "Take Down",
    "Thrash",
    "Double-Edge",
    "Tail Whip",
    "Poison Sting",
    "Twineedle",
    "Pin Missile",
    "Leer",
    "Bite",
    "Growl",
    "Roar",
    "Sing",
    "Supersonic",
    "Sonic Boom",
    "Disable",
    "Acid",
    "Ember",
    "Flamethrower",
    "Mist",
    "Water Gun",
    "Hydro Pump",
    "Surf",
    "Ice Beam",
    "Blizzard",
    "Psybeam",
    "Bubble Beam",
    "Aurora Beam",
    "Hyper Beam",
    "Peck",
    "Drill Peck",
    "Submission",
    "Low Kick",
    "Counter",
    "Seismic Toss",
    "Strength",
    "Absorb",
    "Mega Drain",
    "Leech Seed",
    "Growth",
    "Razor Leaf",
    "Solar Beam",
    "PoisonPowder",
    "Stun Spore",
    "Sleep Powder",
    "Petal Dance",
    "StringShot",
    "Dragon Rage",
    "Fire Spin",
    "ThunderShock",
    "Thunderbolt",
    "Thunder Wave",
    "Thunder",
    "Rock Throw",
    "Earthquake",
    "Fissure",
    "Dig",
    "Toxic",
    "Confusion",
    "Psychic",
    "Hypnosis",
    "Meditate",
    "Agility",
    "Quick Attack",
    "Rage",
    "Teleport",
    "Night Shade",
    "Mimic",
    "Screech",
    "Double Team",
    "Recover",
    "Harden",
    "Minimize",
    "Smokescreen",
    "Confuse Ray",
    "Withdraw",
    "Defense Curl",
    "Barrier",
    "Light Screen",
    "Haze",
    "Reflect",
    "Focus Energy",
    "Bide",
    "Metronome",
    "Mirror Move",
    "SelfDestruct",
    "Egg bomb",
    "Lick",
    "Smog",
    "Sludge",
    "Bone Club",
    "Fire Blast",
    "Waterfall",
    "Clamp",
    "Swift",
    "Skull Bash",
    "Spike Cannon",
    "Constrict",
    "Amnesia",
    "Kinesis",
    "Soft-Boiled",
    "Hi Jump Kick",
    "Glare",
    "Dream Eater",
    "Poison Gas",
    "Barrage",
    "Leech Life",
    "Lovely Kiss",
    "Sky Attack",
    "Transform",
    "Bubble",
    "Dizzy Punch",
    "Spore",
    "Flash",
    "Psywave",
    "Splash",
    "Acid Armor",
    "Crabhammer",
    "Explosion",
    "Fury Swipes",
    "Bonemerang",
    "Rest",
    "Rock Slide",
    "Hyper Fang",
    "Sharpen",
    "Conversion",
    "Tri Attack",
    "Super Fang",
    "Slash",
    "Substitute",
    "Struggle",
    "Fairy Wind",
    "Triple Kick",
    "DrainingKiss",
    "Moonblast",
    "Rage Fist",
    "StrangeSteam",
    "Flame Wheel",
    "Dark Pulse",
    "Night Slash",
    "Play Rough",
    "Burning Mist",
    "Aeroblast",
    "Cotton Spore",
    "Laughing Gas",
    "Nothing",
    "Powder Snow",
    "Miasma",
    "Mach Punch",
    "Scary Face",
    "Feint Attack",
    "Sweet Kiss",
    "Shock Smog",
    "Sludge Bomb",
    "Mud-Slap",
    "Octazooka",
    "Bass Tremor",
    "Zap Cannon",
    "Hyper Voice",
    "Flash Cannon",
    "Iron Defense",
    "Icy Wind",
    "Iron Head",
    "Bone Rush",
    "Air Slash",
    "Outrage",
    "X-Scissor",
    "Giga Drain",
    "Signal Beam",
    "Charm",
    "Rollout",
    "Seed Bomb",
    "Poison Jab",
    "Sharp Point",
    "Spark",
    "3-D Attack",
    "Steel Wing",
    "Cyber Crush",
    "Odd Wave",
    "Dragon Pulse",
    "False Swipe",
    "Nothing",
    "Nothing",
    "Nothing",
    "Nothing",
    "Nothing",
    "Sacred Fire",
    "Nothing",
    "DynamicPunch",
    "Megahorn",
    "DragonBreath",
    "Nothing",
    "Nothing",
    "Nothing",
    "Nothing",
    "Sweet Scent",
    "Iron Tail",
    "Metal Claw",
    "Nothing",
    "Morning Sun",
    "Synthesis",
    "Moonlight",
    "Nothing",
    "Cross Chop",
    "Twister",
    "Nothing",
    "Nothing",
    "Crunch",
    "Nothing",
    "Nothing",
    "ExtremeSpeed",
    "AncientPower",
    "Shadow Ball",
    "Nothing",
    "Rock Smash",
    "Nothing",
    "Dice Roll",
    "Wood Hammer",
    "Twig Slap",
    "Noise Pulse",
    "Nothing",
    NULL
};

const char *MapNames[]=
{
    "000 (0x00) - Gravel Town",
    "001 (0x01) - Seashore City",
    "002 (0x02) - Jaeru City",
    "003 (0x03) - Hayward City",
    "004 (0x04) - Merson City",
    "005 (0x05) - Castro Valley",
    "006 (0x06) - Moraga Town",
    "007 (0x07) - Owsauri City",
    "008 (0x08) - Eagulou City",
    "009 (0x09) - Rijon League Entrance",
    "010 (0x0A) - Botan City",
    "011 (0x0B) - Azalea Town",
    "012 (0x0C) - Route 53",
    "013 (0x0D) - Route 52",
    "014 (0x0E) - Route 59",
    "015 (0x0F) - Route 64",
    "016 (0x10) - Route 57",
    "017 (0x11) - Route 58",
    "018 (0x12) - Route 60",
    "019 (0x13) - Route 54",
    "020 (0x14) - Route 63",
    "021 (0x15) - Route 55",
    "022 (0x16) - Route 62",
    "023 (0x17) - Route 61",
    "024 (0x18) - Final Dungeon Underground Path",
    "025 (0x19) - Final Dungeon Outdoor Path",
    "026 (0x1A) - UNUSED (Azalea header copy)",
    "027 (0x1B) - Old Route 47",
    "028 (0x1C) - Old Route 48",
    "029 (0x1D) - Route 49",
    "030 (0x1E) - Route 66",
    "031 (0x1F) - Route 56",
    "032 (0x20) - UNUSED (Glitched Gravel Town)",
    "033 (0x21) - Route 67",
    "034 (0x22) - Route 65",
    "035 (0x23) - Route 51",
    "036 (0x24) - Route 50",
    "037 (0x25) - Seashore City Player's House 1F",
    "038 (0x26) - Seashore City Player's House 2F",
    "039 (0x27) - Hayward City Town Map House",
    "040 (0x28) - Gravel Town - Tim's Lab",
    "041 (0x29) - UNUSED (PokéCenter)",
    "042 (0x2A) - Gravel Town - PokéMart",
    "043 (0x2B) - Moraga Town - High School Academy",
    "044 (0x2C) - Seashore City - Rival's House",
    "045 (0x2D) - Eagulou City - Gym",
    "046 (0x2E) - Hayward City - Bunker Entrance",
    "047 (0x2F) - Route 57 - Castro Forest Gate",
    "048 (0x30) - Route 52 - Trade House",
    "049 (0x31) - Hayward City - Route 52 Gate",
    "050 (0x32) - Castro Valley - Castro Forest Entrance",
    "051 (0x33) - Castro Forest",
    "052 (0x34) - Botan City - Cave",
    "053 (0x35) - UNUSED (Pewter Museum 2F)",
    "054 (0x36) - Merson City - Gym",
    "055 (0x37) - Moraga Town - Sandshrew House",
    "056 (0x38) - Jaeru City - PokéMart",
    "057 (0x39) - Jaeru City - House",
    "058 (0x3A) - Jaeru City - PokéCenter",
    "059 (0x3B) - Merson Cave 1F",
    "060 (0x3C) - Merson Cave B1F",
    "061 (0x3D) - Final Dungeon Underground Cave Maze 1F",
    "062 (0x3E) - Botan City - Move Relearner & Deleter House",
    "063 (0x3F) - Final Dungeon Underground Cave Maze 1F - Trade Room",
    "064 (0x40) - UNUSED (PokéCenter)",
    "065 (0x41) - Owsauri City - Gym",
    "066 (0x42) - Jaeru City - Bike Shop",
    "067 (0x43) - Moraga Town - PokéMart",
    "068 (0x44) - Route 67 PokéCenter",
    "069 (0x45) - UNUSED (Map 0x3e header copy)",
    "070 (0x46) - UNUSED (Red's Route 5 Gate)",
    "071 (0x47) - Moraga Town - City Underpass Entrance",
    "072 (0x48) - Owsauri City - Daycare",
    "073 (0x49) - Botan City - Route 58 Gate",
    "074 (0x4A) - Route 56 - City Underpass Entrance",
    "075 (0x4B) - UNUSED (Underpass Entrance)",
    "076 (0x4C) - Botan City - Route 59 Gate 1F",
    "077 (0x4D) - Route 52 - Dock Underpass Entrance",
    "078 (0x4E) - UNUSED (Underpass Entrance)",
    "079 (0x4F) - Moraga Town - Prism Museum",
    "080 (0x50) - Route 55 - Dock Underpass Entrance",
    "081 (0x51) - Azalea Town - PokeCenter",
    "082 (0x52) - Final Dungeon Underground Cave Maze B1F",
    "083 (0x53) - Power Plant",
    "084 (0x54) - UNUSED (Red's Route 11 Gate 1F)",
    "085 (0x55) - Final Dungeon Final Cave",
    "086 (0x56) - Botan City - Route 59 Gate 2F",
    "087 (0x57) - Route 49 - Route 50 Gate 1F",
    "088 (0x58) - UNUSED (Bill's House)",
    "089 (0x59) - Castro Valley - PokéCenter",
    "090 (0x5A) - Merson City - Pokémon Fan Club",
    "091 (0x5B) - Castro Valley - PokéMart",
    "092 (0x5C) - Jaeru City - Gym",
    "093 (0x5D) - Seneca Caverns B1F",
    "094 (0x5E) - UNUSED (VERMILION_DOCK)",
    "095 (0x5F) - UNUSED (SS_ANNE_1F)",
    "096 (0x60) - UNUSED (SS_ANNE_2F)",
    "097 (0x61) - Castro Valley - Punch Tutor House",
    "098 (0x62) - UNUSED (SS_ANNE_B1F)",
    "099 (0x63) - Final Dungeon Main Building B3F",
    "100 (0x64) - Castro Valley Dock",
    "101 (0x65) - UNUSED (SS_ANNE_CAPTAINS_ROOM)",
    "102 (0x66) - Final Dungeon Multi Room 1",
    "103 (0x67) - Final Dungeon Multi Room 2",
    "104 (0x68) - Final Dungeon Multi Room 3",
    "105 (0x69) - Slowpoke Well 1F",
    "106 (0x6A) - Route 60 - Route 61 Gate",
    "107 (0x6B) - Route 61 - Route 62 Gate",
    "108 (0x6C) - Eagulou - Gym Entrance Cave",
    "109 (0x6D) - Route 62 - Castro Forest Gate (Hallway)",
    "110 (0x6E) - Route 62 - Castro Forest Gate (Entrance)",
    "111 (0x6F) - International Tunnel 1F",
    "112 (0x70) - UNUSED (Game Corner Prize Room copy)",
    "113 (0x71) - Blanch's Room (Eite 4)",
    "114 (0x72) - Castro Valley - Dock Entrance",
    "115 (0x73) - UNUSED (Seneca Caverns B2F Header Copy)",
    "116 (0x74) - Route 65 - Route 67 Gate",
    "117 (0x75) - Silph Warehouse Overworld",
    "118 (0x76) - Hall Of Fame Room",
    "119 (0x77) - City Underpass (Route 56 - Moraga Town)",
    "120 (0x78) - Champion's Room (Elite 4)",
    "121 (0x79) - Dock Underpass (route 51-52)",
    "122 (0x7A) - Hayward City - Southland Mall 1F",
    "123 (0x7B) - Hayward City - Southland Mall 2F",
    "124 (0x7C) - Hayward City - Southland Mall 3F",
    "125 (0x7D) - Hayward City - Southland Mall 4F",
    "126 (0x7E) - Hayward City - Southland Mall Roof",
    "127 (0x7F) - Hayward City - Southland Mall Elevator",
    "128 (0x80) - Rainbow Tower 1f",
    "129 (0x81) - Rainbow Tower 2f",
    "130 (0x82) - Rainbow Tower 3f",
    "131 (0x83) - Rainbow Tower Rooftop",
    "132 (0x84) - Rainbow Tower Rooftop House",
    "133 (0x85) - Hayward City - PokéCenter",
    "134 (0x86) - Moraga Town - Gym",
    "135 (0x87) - Owsauri City - Casino",
    "136 (0x88) - Hayward City - Southland Mall 5F",
    "137 (0x89) - Owsauri City - Casino Prize Room",
    "138 (0x8A) - Moraga Town - Nation's Burgers",
    "139 (0x8B) - UNUSED (CELADON_CHIEF_HOUSE)",
    "140 (0x8C) - UNUSED (CELADON_HOTEL)",
    "141 (0x8D) - Merson City - PokéCenter",
    "142 (0x8E) - Haunted Forest - Entrance",
    "143 (0x8F) - Haunted Forest - Basement",
    "144 (0x90) - Haunted Forest 1F",
    "145 (0x91) - Haunted Forest 2F",
    "146 (0x92) - Haunted Forest 3F",
    "147 (0x93) - Haunted Forest 4F",
    "148 (0x94) - Haunted Forest 5F",
    "149 (0x95) - Botan City - Mr Rumiko's House",
    "150 (0x96) - Merson City - PokéMart",
    "151 (0x97) - MersonCity - Cubone House",
    "152 (0x98) - Owsauri City - PokéMart",
    "153 (0x99) - Owsauri City - Gambler Husband House",
    "154 (0x9A) - Owsauri City - PokéCenter",
    "155 (0x9B) - Hayward City - HM04 Strength House",
    "156 (0x9C) - Eagulou Park Gate",
    "157 (0x9D) - Castro Valley - Gym",
    "158 (0x9E) - UNUSED (FUCHSIA_MEETING_ROOM)",
    "159 (0x9F) - Silk Tunnel B1F",
    "160 (0xA0) - Silk Tunnel B2F",
    "161 (0xA1) - Mt. Boulder 1f",
    "162 (0xA2) - Mt. Boulder B1F",
    "163 (0xA3) - Castro Valley - Old Rod House",
    "164 (0xA4) - Route 67 - Teleport Scientist House",
    "165 (0xA5) - Castro Manor 1F",
    "166 (0xA6) - Route 57 - Equity Gym",
    "167 (0xA7) - UNUSED (CINNABAR_LAB)",
    "168 (0xA8) - Botan City - Trade House",
    "169 (0xA9) - UNUSED (CINNABAR_LAB_METRONOME_ROOM)",
    "170 (0xAA) - Hayward City - Fossil Lab",
    "171 (0xAB) - Eagulou City - PokéCenter",
    "172 (0xAC) - Eagulou City - PokéMart",
    "173 (0xAD) - UNUSED (Eagulou Pokémart Header Copy)",
    "174 (0xAE) - Rijon League Lobby",
    "175 (0xAF) - UNUSED (COPYCATS_HOUSE_1F)",
    "176 (0xB0) - UNUSED ( COPYCATS_HOUSE_2F)",
    "177 (0xB1) - Azalea Town - Gym",
    "178 (0xB2) - Seashore City - Gym",
    "179 (0xB3) - UNUSED (SAFFRON_PIDGEY_HOUSE)",
    "180 (0xB4) - Botan City - PokéMart",
    "181 (0xB5) - Silph Co. Warehouse 1F",
    "182 (0xB6) - Moraga Town - PokéCenter",
    "183 (0xB7) - Slowpoke Well B1F",
    "184 (0xB8) - Route 60 - Jaeru City Gate 1F",
    "185 (0xB9) - Route 60 - Jaeru City Gate 2F",
    "186 (0xBA) - Rinjoh Veloway North Gate 1F",
    "187 (0xBB) - Rinjoh Veloway North Gate 2F",
    "188 (0xBC) - Moraga Town - HM02 Fly House",
    "189 (0xBD) - Route 61 - Good Rod House",
    "190 (0xBE) - Rinjoh Veloway South Gate 1F",
    "191 (0xBF) - Rinjoh Veloway South Gate 2F",
    "192 (0xC0) - Silk Tunnel 1F",
    "193 (0xC1) - Jaeru City - Route 65 Gate",
    "194 (0xC2) - 30 Years Cave",
    "195 (0xC3) -  Route 49 - Route 50 Gate 2F",
    "196 (0xC4) - Castro Valley - Chansey Trade House",
    "197 (0xC5) - Bunker",
    "198 (0xC6) - Eagulou Park Secret Cave B1F",
    "199 (0xC7) - Final Dungeon Main Building 1F",
    "200 (0xC8) - Final Dungeon Main Building B2F",
    "201 (0xC9) - Final Dungeon Main Building B1F",
    "202 (0xCA) - Final Dungeon Final Island",
    "203 (0xCB) - UNUSED (ROCKET_HIDEOUT_ELEVATOR)",
    "204 (0xCC) - UNUSED (Map 116 header copy)",
    "205 (0xCD) - Route 34 - Old Route 47 - Ilex Forest Gate",
    "206 (0xCE) - UNUSED",
    "207 (0xCF) - Silph Co. Warehouse 2F",
    "208 (0xD0) - Final Dungeon Teleporter Room",
    "209 (0xD1) - Silph Co. Warehouse B1F",
    "210 (0xD2) - International Tunnel B1F",
    "211 (0xD3) - Silph Co. Warehouse 3F",
    "212 (0xD4) - Final Dungeon Underground Cave Maze B1F Ho-Oh Room",
    "213 (0xD5) - Seneca Caverns 1F",
    "214 (0xD6) - Castro Manor 2F",
    "215 (0xD7) - Castro Manor 3F",
    "216 (0xD8) - Castro Manor B1F",
    "217 (0xD9) - Eagulou Park Area 3",
    "218 (0xDA) - Eagulou Park Area 2",
    "219 (0xDB) - Seneca Caverns B2F",
    "220 (0xDC) - Eagulou Park Area 1",
    "221 (0xDD) - Eagulou Park Area 1 House",
    "222 (0xDE) - Route 61 - HM03 Surf House",
    "223 (0xDF) - UNUSED (Eagulou Park House)",
    "224 (0xE0) - Eagulou Park Area 3 House",
    "225 (0xE1) - Eagulou Park Area 2 House",
    "226 (0xE2) - Azalea Town - Ilex Forest Gate",
    "227 (0xE3) - Eagulou Park Secret Cave B2F",
    "228 (0xE4) - Illex Forest",
    "229 (0xE5) - Owsauri City - Name Rater's House",
    "230 (0xE6) - UNUSED (CERULEAN_BADGE_HOUSE)",
    "231 (0xE7) - UNUSED",
    "232 (0xE8) - Silk Tunnel B3F",
    "233 (0xE9) - Final Dungeon Final Island *Pokécenter*",
    "234 (0xEA) - Route 34 (Johto)",
    "235 (0xEB) - Silph Co. Warehouse Manager Room",
    "236 (0xEC) - UNUSED (SILPH_CO_ELEVATOR)",
    "237 (0xED) - UNUSED",
    "238 (0xEE) - UNUSED",
    "239 (0xEF) - Link Trade Room",
    "240 (0xF0) - Link Battle Room",
    "241 (0xF1) - Final Dungeon Healing Room",
    "242 (0xF2) - Final Dungeon Shop",
    "243 (0xF3) - Merson Cave Healing Room",
    "244 (0xF4) - UNUSED (header error?)",
    "245 (0xF5) - Redd's Room (Elite 4)",
    "246 (0xF6) - Jared's Room (Elite 4)",
    "247 (0xF7) - Agatha's Room (Elite 4)",  //This is the actual last map, there's only 248 maps, this is ID 247
    "248 (0xF8) - INVALID",
    "249 (0xF9) - INVALID",
    "250 (0xFA) - INVALID",
    "251 (0xFB) - INVALID",
    "252 (0xFC) - INVALID",
    "253 (0xFD) - INVALID",
    "254 (0xFE) - INVALID",
    "255 (0xFF) - INVALID",
    NULL
};

//A little hacky, the first element shouldn't be there, but works like this right now to work with ...
int data2dex[] =
{
    0,//This shouldn't be there
    112,
    115,
    32,
    35,
    21,
    100,
    34,
    80,
    2,
    103,
    108,
    102,
    88,
    94,
    29,
    31,
    104,
    111,
    131,
    59,
    151,
    130,
    90,
    72,
    92,
    123,
    120,
    9,
    127,
    114,
    152,
    153,
    58,
    95,
    22,
    16,
    79,
    64,
    75,
    113,
    67,
    122,
    106,
    107,
    24,
    47,
    54,
    96,
    76,
    223,
    126,
    183,
    125,
    82,
    109,
    155,
    56,
    86,
    50,
    128,
    156,
    157,
    158,
    83,
    48,
    149,
    159,
    160,
    161,
    84,
    60,
    124,
    146,
    144,
    145,
    132,
    52,
    98,
    162,
    163,
    164,
    37,
    38,
    25,
    26,
    224,
    194,
    147,
    148,
    140,
    141,
    116,
    117,
    166,
    167,
    27,
    28,
    138,
    139,
    39,
    40,
    133,
    136,
    135,
    134,
    66,
    41,
    23,
    46,
    61,
    62,
    13,
    14,
    15,
    218,
    85,
    57,
    51,
    49,
    87,
    168,
    169,
    10,
    11,
    12,
    68,
    170,
    55,
    97,
    42,
    150,
    143,
    129,
    171,
    196,
    89,
    220,
    99,
    91,
    196,
    101,
    36,
    110,
    53,
    105,
    229,
    93,
    63,
    65,
    17,
    18,
    121,
    1,
    3,
    73,
    173,
    118,
    119,
    174,
    175,
    176,
    219,
    77,
    78,
    19,
    20,
    33,
    30,
    74,
    137,
    142,
    192,
    81,
    178,
    179,
    4,
    7,
    5,
    8,
    6,
    180,
    0,
    198,
    182,
    43,
    44,
    45,
    69,
    70,
    71,
    185,
    186,
    189,
    190,
    187,
    188,
    200,
    201,
    133,
    133,
    133,
    184,
    216,
    177,
    221,
    222,
    204,
    217,
    214,
    215,
    209,
    213,
    207,
    208,
    181,
    199,
    202,
    203,
    205,
    206,
    172,
    165,
    197,
    212,
    191,
    211,
    193,
    210,
    195,
    154,
    225,
    226,
    227,
    228, //234 index
    230,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    252, //252 index
    255,
    255,
    255,
    255 //256
};

const char *SpeciesName[]=
{
    "000 No Pokemon",
    "Rhydon",
    "Kangaskhan",
    "NidoranM",
    "Clefairy",
    "Spearow",
    "Voltorb",
    "Nidoking",
    "Slowbro",
    "Ivysaur",
    "Exeggutor",
    "Lickitung",
    "Exeggcute",
    "Grimer",
    "Gengar",
    "NidoranF",
    "Nidoqueen",
    "Cubone",
    "Rhyhorn",
    "Lapras",
    "Arcanine",
    "Mew",
    "Gyarados",
    "Shellder",
    "Tentacool",
    "Gastly",
    "Scyther",
    "Staryu",
    "Blastoise",
    "Pinsir",
    "Tangela",
    "Chikorita",
    "Bayleef",
    "Growlithe",
    "Onix",
    "Fearow",
    "Pidgey",
    "Slowpoke",
    "Kadabra",
    "Graveler",
    "Chansey",
    "Machoke",
    "Mr. Mime",
    "Hitmonlee",
    "Hitmonchan",
    "Arbok",
    "Parasect",
    "Psyduck",
    "Drowzee",
    "Golem",
    "Cranidos",
    "Magmar",
    "Pupitar",
    "Electabuzz",
    "Magneton",
    "Koffing",
    "Cyndaquil",
    "Mankey",
    "Seel",
    "Diglett",
    "Tauros",
    "Quilava",
    "Typhlosion",
    "Totodile",
    "Farfetch'd",
    "Venonat",
    "Dragonite",
    "Croconaw",
    "Feraligatr",
    "Houndour",
    "Doduo",
    "Poliwag",
    "Jynx",
    "Moltres",
    "Articuno",
    "Zapdos",
    "Ditto",
    "Meowth",
    "Krabby",
    "Houndoom",
    "Heracross",
    "Yanma",
    "Vulpix",
    "Ninetales",
    "Pikachu",
    "Raichu",
    "Rampardos",
    "Sneasel",
    "Dratini",
    "Dragonair",
    "Kabuto",
    "Kabutops",
    "Horsea",
    "Seadra",
    "Spinarak",
    "Ariados",
    "Sandshrew",
    "Sandslash",
    "Omanyte",
    "Omastar",
    "Jigglypuff",
    "Wigglytuff",
    "Eevee (Espeon)",
    "Flareon",
    "Jolteon",
    "Vaporeon",
    "Machop",
    "Zubat",
    "Ekans",
    "Paras",
    "Poliwhirl",
    "Poliwrath",
    "Weedle",
    "Kakuna",
    "Beedrill",
    "Raikou",
    "Dodrio",
    "Primeape",
    "Dugtrio",
    "Venomoth",
    "Dewgong",
    "Chinchou",
    "Lanturn",
    "Caterpie",
    "Metapod",
    "Butterfree",
    "Machamp",
    "Swinub",
    "Golduck",
    "Hypno",
    "Golbat",
    "Mewtwo",
    "Snorlax",
    "Magikarp",
    "Piloswine",
    "Tyrogue (Hitmonchan)",
    "Muk",
    "Suicune",
    "Kingler",
    "Cloyster",
    "Tyrogue (Hitmonlee)",
    "Electrode",
    "Clefable",
    "Weezing",
    "Persian",
    "Marowak",
    "Tyrogue (Hitmontop)/Noibat",
    "Haunter",
    "Abra",
    "Alakazam",
    "Pidgeotto",
    "Pidgeot",
    "Starmie",
    "Bulbasaur",
    "Venusaur",
    "Tentacruel",
    "Natu",
    "Goldeen",
    "Seaking",
    "Xatu",
    "Mareep",
    "Flaaffy",
    "Entei",
    "Ponyta",
    "Rapidash",
    "Rattata",
    "Raticate",
    "Nidorino",
    "Nidorina",
    "Geodude",
    "Porygon",
    "Aerodactyl",
    "Gligar",
    "Magnemite",
    "Marill",
    "Azumarill",
    "Charmander",
    "Squirtle",
    "Charmeleon",
    "Wartortle",
    "Charizard",
    "Murkrow",
    "Ghost (MissingNo.)",
    "Misdreavus",
    "Larvitar",
    "Oddish",
    "Gloom",
    "Vileplume",
    "Bellsprout",
    "Weepinbell",
    "Victreebel",
    "Phanpy",
    "Donphan",
    "Togepi",
    "Togetic",
    "Wooper",
    "Quagsire",
    "Espeon",
    "Umbreon",
    "Eevee (Umbreon)",
    "Eevee (Leafeon)",
    "Eevee (Glaceon)",
    "Tyranitar",
    "Crobat",
    "Ampharos",
    "Lugia",
    "Ho-Oh",
    "Magnezone",
    "Politoed",
    "Rhyperior",
    "Blissey",
    "Tangrowth",
    "Kingdra",
    "Porygon2",
    "Porygon-Z",
    "Honchkrow",
    "Mismagius",
    "Leafeon",
    "Glaceon",
    "Electivire",
    "Magmortar",
    "Mamoswine",
    "Yanmega",
    "Hitmontop",
    "Slowking",
    "Togekiss",
    "Steelix",
    "Gliscor",
    "Scizor",
    "Weavile",
    "Meganium",
    "Sylveon",
    "Annihilape",
    "G.Weezing",
    "Lickilikky",
    "Noivern",
    "Glitch Phancero",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "Phancero Extra",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "Phancero",
    "?????",
    "?????",
    "?????",
    NULL
};

const char *ItemName[]=
{
    "00GLITCH",
    "Master Ball",
    "Ultra Ball",
    "Great Ball",
    "Pokeball",
    "Town Map",
    "Bycicle",
    "07GLITCH",
    "Park Ball",
    "08GLITCH",
    "Moon Stone",
    "Antidote",
    "Burn Heal",
    "Ice Heal",
    "Awakening",
    "Paralyze Heal",
    "Full Restore",
    "Max Potion",
    "Hyper Potion",
    "Super Potion",
    "Potion",
    "09GLITCH",
    "10GLITCH",
    "Red Orb",
    "Blue Orb",
    "Green Orb",
    "Dusk Stone",
    "Up-Grade",
    "Shiny Stone",
    "Escape Rope",
    "Repel",
    "Skull Fossil",
    "Fire Stone",
    "Thunder Stone",
    "Water Stone",
    "HP Up",
    "Protein",
    "Iron",
    "Carbos",
    "Calcium",
    "Rare Candy",
    "Dome Fossil",
    "Helix Fossil",
    "Mist Stone",
    "Dubious Disk",
    "Bike Voucher",
    "X Accuracy",
    "Leaf Stone",
    "Card Key",
    "Nugget",
    "PP Up",
    "Poké Doll",
    "Full Heal",
    "Revive",
    "Max Revive",
    "Guard Spec.",
    "Super Repel",
    "Max Repel",
    "Dire Hit",
    "GLITCH (COIN)",
    "Beer Keg",
    "Soda",
    "Lemonade",
    "S.S. Ticket",
    "Red Amulet",
    "X Attack",
    "X Defend",
    "X Speed",
    "X Special",
    "Coin Case",
    "Tim's Pizza",
    "Item Finder",
    "Virus Scan",
    "Poké Flute",
    "GLITCH",
    "Exp. All",
    "Old Rod",
    "Good Rod",
    "Super Rod",
    "PP UP",
    "Ether",
    "Max Ether",
    "Elixir",
    "Max Elixir",
    "Metal Coat",
    "Magmarizer",
    "Electrizer",
    "Trade Stone",
    "Protector",
    "Razor Fang",
    "Razor Claw",
    "King's Rock",
    "Dragon Scale",
    "Pearl",
    "Big Pearl",
    "Stardust",
    "Star Piece",
    "Tiny Mushroom",
    "Mushroom",
    "Gold Leaf",
    "Sapphire Egg",
    "Brick Piece/Ice Stone",
    "Rare Bone",
    "Coronet Stone",
    "Ruby Egg",
    "Gold Egg",
    "Crystal Egg",
    "Emerald Egg",
    "Prism Key",
    "Silver Egg",
    "Magic Wand ",
    "1F",
    "2F",
    "3F",
    "4F",
    "5F",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "HM01",
    "HM02",
    "HM03",
    "HM04",
    "HM05",
    "TM01",
    "TM02",
    "TM03",
    "TM04",
    "TM05",
    "TM06",
    "TM07",
    "TM08",
    "TM09",
    "TM10",
    "TM11",
    "TM12",
    "TM13",
    "TM14",
    "TM15",
    "TM16",
    "TM17",
    "TM18",
    "TM19",
    "TM20",
    "TM21",
    "TM22",
    "TM23",
    "TM24",
    "TM25",
    "TM26",
    "TM27",
    "TM28",
    "TM29",
    "TM30",
    "TM31",
    "TM32",
    "TM33",
    "TM34",
    "TM35",
    "TM36",
    "TM37",
    "TM38",
    "TM39",
    "TM40",
    "TM41",
    "TM42",
    "TM43",
    "TM44",
    "TM45",
    "TM46",
    "TM47",
    "TM48",
    "TM49",
    "TM50",
    "TM51",
    "TM52",
    "TM53",
    "TM54",
    "TM55",
    NULL
};

const char *DexOrderNames[]=
{
    "NOMON",
    "Bulbasaur",
    "Ivysaur",
    "Venusaur",
    "Charmander",
    "Charmeleon",
    "Charizard",
    "Squirtle",
    "Wartortle",
    "Blastoise",
    "Caterpie",
    "Metapod",
    "Butterfree",
    "Weedle",
    "Kakuna",
    "Beedrill",
    "Pidgey",
    "Pidgeotto",
    "Pidgeot",
    "Rattata",
    "Raticate",
    "Spearow",
    "Fearow",
    "Ekans",
    "Arbok",
    "Pikachu",
    "Raichu",
    "Sandshrew",
    "Sandslash",
    "NidoranF",
    "Nidorina",
    "Nidoqueen",
    "NidoranM",
    "Nidorino",
    "Nidoking",
    "Clefairy",
    "Clefable",
    "Vulpix",
    "Ninetales",
    "Jigglypuff",
    "Wigglytuff",
    "Zubat",
    "Golbat",
    "Oddish",
    "Gloom",
    "Vileplume",
    "Paras",
    "Parasect",
    "Venonat",
    "Venomoth",
    "Diglett",
    "Dugtrio",
    "Meowth",
    "Persian",
    "Psyduck",
    "Golduck",
    "Mankey",
    "Primeape",
    "Growlithe",
    "Arcanine",
    "Poliwag",
    "Poliwhirl",
    "Poliwrath",
    "Abra",
    "Kadabra",
    "Alakazam",
    "Machop",
    "Machoke",
    "Machamp",
    "Bellsprout",
    "Weepinbell",
    "Victreebel",
    "Tentacool",
    "Tentacruel",
    "Geodude",
    "Graveler",
    "Golem",
    "Ponyta",
    "Rapidash",
    "Slowpoke",
    "Slowbro",
    "Magnemite",
    "Magneton",
    "Farfetch'd",
    "Doduo",
    "Dodrio",
    "Seel",
    "Dewgong",
    "Grimer",
    "Muk",
    "Shellder",
    "Cloyster",
    "Gastly",
    "Haunter",
    "Gengar",
    "Onix",
    "Drowzee",
    "Hypno",
    "Krabby",
    "Kingler",
    "Voltorb",
    "Electrode",
    "Exeggcute",
    "Exeggutor",
    "Cubone",
    "Marowak",
    "Hitmonlee",
    "Hitmonchan",
    "Lickitung",
    "Koffing",
    "Weezing",
    "Rhyhorn",
    "Rhydon",
    "Chansey",
    "Tangela",
    "Kangaskhan",
    "Horsea",
    "Seadra",
    "Goldeen",
    "Seaking",
    "Staryu",
    "Starmie",
    "Mr. Mime",
    "Scyther",
    "Jynx",
    "Electabuzz",
    "Magmar",
    "Pinsir",
    "Tauros",
    "Magikarp",
    "Gyarados",
    "Lapras",
    "Ditto",
    "Eevee",
    "Vaporeon",
    "Jolteon",
    "Flareon",
    "Porygon",
    "Omanyte",
    "Omastar",
    "Kabuto",
    "Kabutops",
    "Aerodactyl",
    "Snorlax",
    "Articuno",
    "Zapdos",
    "Moltres",
    "Dratini",
    "Dragonair",
    "Dragonite",
    "Mewtwo",
    "Mew",
    "Chikorita",
    "Bayleef",
    "Meganium",
    "Cyndaquil",
    "Quilava",
    "Typhlosion",
    "Totodile",
    "Croconaw",
    "Feraligatr",
    "Houndour",
    "Houndoom",
    "Heracross",
    "Yanma",
    "Yanmega",
    "Spinarak",
    "Ariados",
    "Chinchou",
    "Lanturn",
    "Swinub",
    "Piloswine",
    "Mamoswine",
    "Natu",
    "Xatu",
    "Mareep",
    "Flaaffy",
    "Ampharos",
    "Marill",
    "Azumarill",
    "Murkrow",
    "Honchkrow",
    "Larvitar",
    "Pupitar",
    "Tyranitar",
    "Phanpy",
    "Donphan",
    "Wooper",
    "Quagsire",
    "Togepi",
    "Togetic",
    "Togekiss",
    "Gligar",
    "Gliscor",
    "Sneasel",
    "Weavile",
    "Tyrogue",
    "Hitmontop",
    "Misdreavus",
    "Mismagius",
    "Espeon",
    "Umbreon",
    "Leafeon",
    "Glaceon",
    "Magnezone",
    "Electivire",
    "Magmortar",
    "Porygon2",
    "Porygon-Z",
    "Tangrowth",
    "Scizor",
    "Steelix",
    "Slowking",
    "Kingdra",
    "Rhyperior",
    "Blissey",
    "Crobat",
    "Politoed",
    "Raikou",
    "Entei",
    "Suicune",
    "Lugia",
    "Ho-Oh",
    "Cranidos",
    "Rampardos",
    "Sylveon",
    "Annihilape",
    "G.Weezing",
    "Lickilicky",
    "Noibat",
    "Noivern",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "Phancero",
    "?????",
    "?????",
    "?????",
    NULL
};

const char *GrowthRates[]=
{
    "Medium Fast",
    "Slightly Fast",
    "Slightly Slow",
    "Medium Slow",
    "Fast",
    "Slow",
    NULL
};

const char *Types[]=
{
	"NORMAL",       //$00
	"FIGHTING",       //$01
	"FLYING",         //$02
	"POISON",         //$03
	"GROUND",         //$04
	"ROCK",           //$05
	"BIRD",           //$06
	"BUG",            //$07
	"GHOST",          //$08
    "STEEL",    //&09
    "STRUGGLE",
    "0B",
    "0C",
    "WIND",
    "SOUND", //$0E
    "TRI",
    "10",
    "11",
    "12",
    "13",
    "FIRE",         //$14
	"WATER",        //$15
	"GRASS",       //$16
	"ELECTRIC",     //$17
	"PSYCHIC", //$18
	"ICE",          //$19
	"DRAGON",       //$1A
    "DARK", //$1B
    "WOOD", //$1C
    "GAS", //1D
    "ABNORMAL", //$1E
    "FAIRY", //$1F
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    NULL
};

const char *TypesTable[]=
{
	"NORMAL  ",       //$00
	"FIGHTING",       //$01
	"FLYING  ",         //$02
	"POISON  ",         //$03
	"GROUND  ",         //$04
	"ROCK    ",           //$05
	"BIRD    ",           //$06
	"BUG     ",            //$07
	"GHOST   ",          //$08
    "STEEL   ",    //&09
    "STRUGGLE",
    "0B",
    "0C",
    "WIND    ",
    "SOUND   ", //$0E
    "TRI     ",
    "10",
    "11",
    "12",
    "13",
    "FIRE    ",         //$14
	"WATER   ",        //$15
	"GRASS   ",       //$16
	"ELECTR  ",     //$17
	"PSYCHIC ", //$18
	"ICE     ",          //$19
	"DRAGON  ",       //$1A
    "DARK    ", //$1B
    "WOOD    ", //$1C
    "GAS     ", //1D
    "ABNORMAL", //$1E
    "FAIRY   ", //$1F
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    NULL
};

const int TypesMatchesIds[]=
{
    0x07, //Bug
    0x1B, //Dark
    0x1A, //Dragon
    0x17, //Electric
    0x1F, //Fairy
    0x01, //Fighting
    0x14, //Fire
    0x02, //Flying
    0x08, //Ghost
    0x16, //Grass
    0x04, //Ground
    0x19, //Ice
    0x00, //Normal
    0x03, //Poison
    0x18, //Psychic
    0x05, //Rock
    0x09, //Steel
    0x15, //Water
    0x0E, //Sound
    0x1D, //Gas
    0x1E, //Abnormal
    0x0D, //Wind
    0x1C, //Wood
    0x0F //Tri
};

const char* TypesMatchesNames[]=
{
    "BUG     ",            //$07
    "DARK    ", //$1B
	"DRAGON  ",       //$1A
	"ELECTR  ",     //$17
    "FAIRY   ", //$1F
	"FIGHTING",       //$01
    "FIRE    ",         //$14
	"FLYING  ",         //$02
	"GHOST   ",          //$08
	"GRASS   ",       //$16
	"GROUND  ",         //$04
	"ICE     ",          //$19
	"NORMAL  ",       //$00
	"POISON  ",         //$03
	"PSYCHIC ", //$18
	"ROCK    ",           //$05
    "STEEL   ",    //&09
	"WATER   ",        //$15
    "SOUND   ", //$0E
    "GAS     ", //1D
    "ABNORMAL", //$1E
    "WIND    ", //$0D
    "WOOD    ", //$1C
    "TRI     ", //$0F
    NULL
};

/*
const int TypesMatchesIds[]=
{
    0x00, //Normal
    0x01, //Fighting
    0x02, //Flying
    0x03, //Poison
    0x04, //Ground
    0x05, //Rock
    0x07, //Bug
    0x08, //Ghost
    0x09, //Steel
    0x0D, //Wind
    0x0E, //Sound
    0x0F, //Tri
    0x14, //Fire
    0x15, //Water
    0x16, //Grass
    0x17, //Electric
    0x18, //Psyichic
    0x19, //Ice
    0x1A, //Dragon
    0x1B, //Dark
    0x1C, //Wood
    0x1D, //Gas
    0x1E, //Abnormal
    0x1F //Fairy
};

const char* TypesMatchesNames[]=
{
	"NORMAL  ",       //$00
	"FIGHTING",       //$01
	"FLYING  ",         //$02
	"POISON  ",         //$03
	"GROUND  ",         //$04
	"ROCK    ",           //$05
	"BUG     ",            //$07
	"GHOST   ",          //$08
    "STEEL   ",    //&09
    "WIND    ", //$0D
    "SOUND   ", //$0E
    "TRI     ", //$0F
    "FIRE    ",         //$14
	"WATER   ",        //$15
	"GRASS   ",       //$16
	"ELECTR  ",     //$17
	"PSYCHIC ", //$18
	"ICE     ",          //$19
	"DRAGON  ",       //$1A
    "DARK    ", //$1B
    "WOOD    ", //$1C
    "GAS     ", //1D
    "ABNORMAL", //$1E
    "FAIRY   ", //$1F
    NULL
};
*/
const char *TM_HM[]=
{
    "TM01: Dynamicpunch",
    "TM02: Razor Wind",
    "TM03: Swords Dance",
    "TM04: Aeroblast/Air Slash",
    "TM05: Triple Kick/Dizzy Punch",
    "TM06: Toxic",
    "TM07: Horn Drill",
    "TM08: Body Slam",
    "TM09: Take Down",
    "TM10: Double-Edge",
    "TM11: Bubblebeam/Signal Beam",
    "TM12: Octazooka",
    "TM13: Ice Beam",
    "TM14: Blizzard",
    "TM15: Hyper Beam",
    "TM16: Pay Day",
    "TM17: Submission",
    "TM18: Counter",
    "TM19: Seismic Toss",
    "TM20: Rage/Steel Wing",
    "TM21: Giga Drain",
    "TM22: Solarbeam",
    "TM23: Dragonbreath",
    "TM24: Thunderbolt",
    "TM25: Thunder",
    "TM26: Earthquake",
    "TM27: Fissure",
    "TM28: Dig",
    "TM29: Psychic",
    "TM30: Shadow Ball",
    "TM31: Mimic",
    "TM32: Double Team",
    "TM33: Reflect",
    "TM34: Bide/Burning Mist",
    "TM35: Metronome",
    "TM36: Sludge Bomb",
    "TM37: Megahorn",
    "TM38: Flamethower",
    "TM39: Swift",
    "TM40: Skull Bash",
    "TM41: Wood Hammer/Seed Bomb",
    "TM42: Dream Eater",
    "TM43: Sky Attack",
    "TM44: Rest",
    "TM45: Thunder Wave",
    "TM46: Noise Pulse",
    "TM47: Explosion",
    "TM48: Rock Slide",
    "TM49: Tri Attack",
    "TM50: Substitute",
    "HM01: Cut",
    "HM02: Fly",
    "HM03: Surf",
    "HM04: Strength",
    "HM05: Flash",
    NULL
};

const char *EVO_TYPE[]=
{
    "NONE    ",
    "EV_LEVEL",
	"EV_ITEM ",
	"EV_TRADE",
	"EV_GEO",
	"EV_ATK",
	"EV_DEF",
	"EV_ATKDEF",
	NULL
};

const char *TRAINER_CLASS[]=
{
    "Nobody",
    "Youngster",
    "Bug Catcher",
    "Lass",
    "Sailor",
    "Jr Trainer M",
    "Jr Trainer F",
    "Pokemaniac",
    "Super Nerd",
    "Hiker",
    "Biker",
    "Burglar",
    "Engineer",
    "PaletteBlack", //Unused Jugler
    "Fisher",
    "Swimmer",
    "Cue Ball",
    "Gambler",
    "Beauty",
    "Telekinetic", // Psychic in original red
    "Rocker",
    "Juggler",
    "Tamer",
    "Bird Keeper",
    "Blackbelt",
    "Rival1",
    "Palette Red",
    "Bugsy",
    "Scientist",
    "Giovanni",
    "Rocket",
    "Cooltrainer M",
    "Cooltrainer F",
    "Jared",
    "Karpman",
    "Lily",
    "Sparky",
    "Lois",
    "Koji",
    "Joe",
    "Sheryl",
    "Gentleman",
    "Rival2",
    "Rival3",
    "Redd",
    "Channeler",
    "Agatha",
    "Blanch",
    NULL
};

//Number of teams in each trainer class
const int TrainerClassTeams[] =
{
    15, //#01 Youngster
    17, //#02 Bug Catcher
    18, //#03 Lass
    8, //#04 Sailor
    9, //#05 Jr Trainer M
    24, //#06 Jr Trainer F
    7, //#07 Pokemaniac
    12, //#08 Super Nerd
    14, //#09 Hiker
    15, //#10 Biker
    9, //#11 Burglar
    3, //#12 Engineer
    3, //#13 PaletteBlack (teams unused, special trainer class)
    11, //#14 Fisher
    15, //#15 Swimmer
    9, //#16 Cue Ball
    7, //#17 Gambler
    15, //#18 Beauty
    5, //#19 Telekinetic
    3, //#20 Rocker
    8, //#21 Juggler
    6, //#22 Tamer
    17, //#23 Bird Keeper
    9, //#24 Blackbelt
    9, //#25 Mura1 (teams unused, special trainer class)
    3, //#26 Palette Red (teams unused, special trainer class)
    1, //#27 Bugsy (teams unused, special trainer class)
    13, //#28 Scientist
    3, //#29 Giovanni (teams unused, special trainer class)
    41, //#30 Rocket
    10, //#31 Cooltrainer M
    8, //#32 Cooltrainer F
    1, //#33 Jared (teams unused, special trainer class)
    1, //#34 Karpman (teams unused, special trainer class)
    1, //#35 Lily (teams unused, special trainer class)
    1, //#36 Sparky (teams unused, special trainer class)
    1, //#37 Lois (teams unused, special trainer class)
    1, //#38 Koji (teams unused, special trainer class)
    1, //#39 Joe (teams unused, special trainer class)
    1, //#40 Sheryl (teams unused, special trainer class)
    5, //#41 Gentleman
    12, //#42 Mura2 (teams unused, special trainer class)
    3, //#43 Mura3 (teams unused, special trainer class)
    1, //#44 Redd (teams unused, special trainer class)
    24, //#45 Channeler
    1, //#46 Agatha (teams unused, special trainer class)
    1 //#47 Blanch (teams unused, special trainer class)
};

const uint16_t ItemAIPointers[19]=
{
    0x65e9,
    0x65ef,
    0x65f5,
    0x65fb,
    0x6601,
    0x6614,
    0x661c,
    0x6622,
    0x6628,
    0x6634,
    0x663a,
    0x6640,
    0x664c,
    0x6658,
    0x6664,
    0x6670,
    0x6676,
    0x6687,
    0x6693
};

const char *ItemAINames[]=
{
    "JugglerAI",
    "BlackbeltAI",
    "GiovanniAI",
    "CooltrainerMAI",
    "CooltrainerFAI",
    "BrockAI",
    "MistyAI",
    "LtSurgeAI",
    "ErikaAI",
    "KogaAI",
    "BlaineAI",
    "SabrinaAI",
    "Rival2AI",
    "Rival3AI",
    "LoreleiAI",
    "BrunoAI",
    "AgathaAI",
    "LanceAI",
    "GenericAI",
    NULL
};

const char *ItemAIItems[]=
{
    "Switch Mon 25% chance",
    "Use X Attack 13% chance",
    "Use Guard Spec 25% chance",
    "Use X Attack 25% chance",
    "Use Hyper Potion or switch 25% chance",
    "Use Full Heal",
    "Use X Defense 25% chance",
    "Use X Speed 25% chance",
    "Use Super Potion 50% chance",
    "Use X Attack 25% chance",
    "Use Super Potion 25% chance",
    "Use Hyper Potion 25% chance",
    "Use Potion 13% chance",
    "Use Full Restore 13% chance",
    "Use Super Potion 50% chance",
    "Use X Defense 25 chance",
    "Use Super Potion 50% / Switch Mon 8% chance",
    "Use Hyper Potion 50% chance",
    "Nothing",
    NULL
};

const char *EncounterProbabilities[]=
{
  "19.9%", //slot 0
  "19.9%", //slot 1
  "15.2%", //slot 2
  "09.8%", //slot 3
  "09.8%", //slot 4
  "09.8%", //slot 5
  "05.1%", //slot 6
  "05.1%", //slot 7
  "04.3%", //slot 8
  "01.2%", //slot 9
  NULL
};

