//https://github.com/pret/pokered/blob/6b5be9129cabe72b9f775b02db1bf7e7169153da/data/moves/animations.asm
const char *Animations[]=
{
    "0x00",//move table starts with pound, but pound is move 01, not 00
    "PoundAnim",
    "KarateChopAnim",
    "DoubleSlapAnim",
    "CometPunchAnim",
    "MegaPunchAnim",
    "PayDayAnim",
    "FirePunchAnim",
    "IcePunchAnim",
    "ThunderPunchAnim",
    "ScratchAnim",
    "VicegripAnim",
    "GuillotineAnim",
    "RazorWindAnim",
    "SwordsDanceAnim",
    "CutAnim",
    "GustAnim",
    "WingAttackAnim",
    "WhirlwindAnim",
    "FlyAnim",
    "BindAnim",
    "SlamAnim",
    "VineWhipAnim",
    "StompAnim",
    "DoubleKickAnim",
    "MegaKickAnim",
    "JumpKickAnim",
    "RollingKickAnim",
    "SandAttackAnim",
    "HeatButtAnim",
    "HornAttackAnim",
    "FuryAttackAnim",
    "HornDrillAnim",
    "TackleAnim",
    "BodySlamAnim",
    "WrapAnim",
    "TakeDownAnim",
    "ThrashAnim",
    "DoubleEdgeAnim",
    "TailWhipAnim",
    "PoisonStingAnim",
    "TwineedleAnim",
    "PinMissileAnim",
    "LeerAnim",
    "BiteAnim",
    "GrowlAnim",
    "RoarAnim",
    "SingAnim",
    "SupersonicAnim",
    "SonicBoomAnim",
    "DisableAnim",
    "AcidAnim",
    "EmberAnim",
    "FlamethrowerAnim",
    "MistAnim",
    "WaterGunAnim",
    "HydroPumpAnim",
    "SurfAnim",
    "IceBeamAnim",
    "BlizzardAnim",
    "PsyBeamAnim",
    "BubbleBeamAnim",
    "AuroraBeamAnim",
    "HyperBeamAnim",
    "PeckAnim",
    "DrillPeckAnim",
    "SubmissionAnim",
    "LowKickAnim",
    "CounterAnim",
    "SeismicTossAnim",
    "StrengthAnim",
    "AbsorbAnim",
    "MegaDrainAnim",
    "LeechSeedAnim",
    "GrowthAnim",
    "RazorLeafAnim",
    "SolarBeamAnim",
    "PoisonPowderAnim",
    "StunSporeAnim",
    "SleepPowderAnim",
    "PetalDanceAnim",
    "StringShotAnim",
    "DragonRageAnim",
    "FireSpinAnim",
    "ThunderShockAnim",
    "ThunderBoltAnim",
    "ThunderWaveAnim",
    "ThunderAnim",
    "RockThrowAnim",
    "EarthquakeAnim",
    "FissureAnim",
    "DigAnim",
    "ToxicAnim",
    "ConfusionAnim",
    "PsychicAnim",
    "HypnosisAnim",
    "MeditateAnim",
    "AgilityAnim",
    "QuickAttackAnim",
    "RageAnim",
    "TeleportAnim",
    "NightShadeAnim",
    "MimicAnim",
    "ScreechAnim",
    "DoubleTeamAnim",
    "RecoverAnim",
    "HardenAnim",
    "MinimizeAnim",
    "SmokeScreenAnim",
    "ConfuseRayAnim",
    "WithdrawAnim",
    "DefenseCurlAnim",
    "BarrierAnim",
    "LightScreenAnim",
    "HazeAnim",
    "ReflectAnim",
    "FocusEnergyAnim",
    "BideAnim",
    "MetronomeAnim",
    "MirrorMoveAnim",
    "SelfdestructAnim",
    "EggBombAnim",
    "LickAnim",
    "SmogAnim",
    "SludgeAnim",
    "BoneClubAnim",
    "FireBlastAnim",
    "WaterfallAnim",
    "ClampAnim",
    "SwiftAnim",
    "SkullBashAnim",
    "SpikeCannonAnim",
    "ConstrictAnim",
    "AmnesiaAnim",
    "KinesisAnim",
    "SoftboiledAnim",
    "HiJumpKickAnim",
    "GlareAnim",
    "DreamEaterAnim",
    "PoisonGasAnim",
    "BarrageAnim",
    "LeechLifeAnim",
    "LovelyKissAnim",
    "SkyAttackAnim",
    "TransformAnim",
    "BubbleAnim",
    "DizzyPunchAnim",
    "SporeAnim",
    "FlashAnim",
    "PsywaveAnim",
    "SplashAnim",
    "AcidArmorAnim",
    "CrabHammerAnim",
    "ExplosionAnim",
    "FurySwipesAnim",
    "BonemerangAnim",
    "RestAnim",
    "RockSlideAnim",
    "HyperFangAnim",
    "SharpenAnim",
    "ConversionAnim",
    "TriAttackAnim",
    "SuperFangAnim",
    "SlashAnim",
    "SubstituteAnim",
    "StruggleAnim",
    //Move Animations end here
    "ShowPicAnim",
    "EnemyFlashAnim",
    "PlayerFlashAnim",
    "EnemyHUDShakeAnim",
    "TradeBallDropAnim",
    "TradeBallAppear1Anim",
    "TradeBallAppear2Anim",
    "TradeBallPoofAnim",
    "XStatItemAnim",
    "XStatItemAnim",
    "ShrinkingSquareAnim",
    "ShrinkingSquareAnim",
    "XStatItemBlackAnim",
    "XStatItemBlackAnim",
    "ShrinkingSquareBlackAnim",
    "ShrinkingSquareBlackAnim",
    "UnusedAnim",
    "UnusedAnim",
    "ParalyzeAnim",
    "ParalyzeAnim",
    "PoisonAnim",
    "PoisonAnim",
    "SleepPlayerAnim",
    "SleepEnemyAnim",
    "ConfusedPlayerAnim",
    "ConfusedEnemyAnim",
    "FaintAnim",
    "BallTossAnim",
    "BallShakeAnim",
    "BallPoofAnim",
    "BallBlockAnim",
    "GreatTossAnim",
    "UltraTossAnim",
    "ShakeScreenAnim",
    "HidePicAnim",
    "ThrowRockAnim",
    "ThrowBaitAnim",
    //Combat animations end here
    "ZigZagScreenAnim",
    "TripleKickAnim",
    "SacredFireAnim",
    "FeintAttackAnim",
    NULL
};

//https://github.com/pret/pokered/blob/6b5be9129cabe72b9f775b02db1bf7e7169153da/constants/move_effect_constants.asm
const char *MoveEffects[]=
{
    "NO_ADDITIONAL_EFFECT",
    "$01_CONFUSION_20P_SIDE_EFFECT(BROWN)",
    "POISON_SIDE_EFFECT1",
    "DRAIN_HP_EFFECT",
    "BURN_SIDE_EFFECT1",
    "FREEZE_SIDE_EFFECT",
    "PARALYZE_SIDE_EFFECT1",
    "EXPLODE_EFFECT",
    "DREAM_EATER_EFFECT",
    "MIRROR_MOVE_EFFECT",
    "ATTACK_UP1_EFFECT",
    "DEFENSE_UP1_EFFECT",
    "SPEED_UP1_EFFECT",
    "SPECIAL_UP1_EFFECT",
    "ACCURACY_UP1_EFFECT",
    "EVASION_UP1_EFFECT",
    "PAY_DAY_EFFECT",
    "SWIFT_EFFECT",
    "ATTACK_DOWN1_EFFECT",
    "DEFENSE_DOWN1_EFFECT",
    "SPEED_DOWN1_EFFECT",
    "SPECIAL_DOWN1_EFFECT",
    "ACCURACY_DOWN1_EFFECT",
    "EVASION_DOWN1_EFFECT",
    "CONVERSION_EFFECT",
    "HAZE_EFFECT",
    "BIDE_EFFECT",
    "THRASH_PETAL_DANCE_EFFECT",
    "SWITCH_AND_TELEPORT_EFFECT",
    "TWO_TO_FIVE_ATTACKS_EFFECT",
    "$1E_TRIPLE KICK_EFFECT(BROWN)",
    "FLINCH_SIDE_EFFECT1",
    "SLEEP_EFFECT",
    "POISON_SIDE_EFFECT2",
    "BURN_SIDE_EFFECT2",
    "$23_HITANDCONFUSE_EFFECT(BROWN)",
    "PARALYZE_SIDE_EFFECT2",
    "FLINCH_SIDE_EFFECT2",
    "OHKO_EFFECT",
    "CHARGE_EFFECT",
    "SUPER_FANG_EFFECT",
    "SPECIAL_DAMAGE_EFFECT",
    "TRAPPING_EFFECT",
    "FLY_EFFECT",
    "ATTACK_TWICE_EFFECT",
    "JUMP_KICK_EFFECT",
    "MIST_EFFECT",
    "FOCUS_ENERGY_EFFECT",
    "RECOIL_EFFECT",
    "CONFUSION_EFFECT",
    "ATTACK_UP2_EFFECT",
    "DEFENSE_UP2_EFFECT",
    "SPEED_UP2_EFFECT",
    "SPECIAL_UP2_EFFECT",
    "ACCURACY_UP2_EFFECT",
    "EVASION_UP2_EFFECT",
    "HEAL_EFFECT",
    "TRANSFORM_EFFECT",
    "ATTACK_DOWN2_EFFECT",
    "DEFENSE_DOWN2_EFFECT",
    "SPEED_DOWN2_EFFECT",
    "SPECIAL_DOWN2_EFFECT",
    "ACCURACY_DOWN2_EFFECT",
    "EVASION_DOWN2_EFFECT",
    "LIGHT_SCREEN_EFFECT",
    "REFLECT_EFFECT",
    "POISON_EFFECT",
    "PARALYZE_EFFECT",
    "ATTACK_DOWN_SIDE_EFFECT",
    "DEFENSE_DOWN_SIDE_EFFECT",
    "SPEED_DOWN_SIDE_EFFECT",
    "SPECIAL_DOWN_SIDE_EFFECT",
    "ACCURACY_DOWN_SIDE_EFFECT (BROWN)",
    "unused_$49",
    "unused_$4A",
    "$4B_TRIATTACK_SIDE_EFFECT3 (BROWN)",
    "CONFUSION_SIDE_EFFECT",
    "TWINEEDLE_EFFECT",
    "$4E_FLINCH_SIDE_EFFECT3 (20% BROWN)",
    "SUBSTITUTE_EFFECT",
    "HYPER_BEAM_EFFECT",
    "RAGE_EFFECT",
    "MIMIC_EFFECT",
    "METRONOME_EFFECT",
    "LEECH_SEED_EFFECT",
    "SPLASH_EFFECT",
    "DISABLE_EFFECT",
    NULL
};

const char *MoveNames[]=
{
    "00_Glitch move",
    "Pound",
    "Karate Chop",
    "Double Slap",
    "Comet Punch",
    "Mega Punch",
    "Pay Day",
    "Fire Punch",
    "Ice Punch",
    "ThunderPunch",
    "Scratch",
    "Vise Grip",
    "Guillotine",
    "Razor Wind",
    "Swords Dance",
    "Cut",
    "Gust",
    "Wing Attack",
    "Whirlwind",
    "Fly",
    "Bind",
    "Slam",
    "Vine Whip",
    "Stomp",
    "Double Kick",
    "Mega Kick",
    "Jump Kick",
    "Rolling Kick",
    "Sand Attack",
    "Headbutt",
    "Horn Attack",
    "Fury Attack",
    "Horn Drill",
    "Tackle",
    "Body Slam",
    "Wrap",
    "Take Down",
    "Thrash",
    "Double-Edge",
    "Tail Whip",
    "Poison Sting",
    "Twineedle",
    "Pin Missile",
    "Leer",
    "Bite",
    "Growl",
    "Roar",
    "Sing",
    "Supersonic",
    "Sonic Boom",
    "Disable",
    "Acid",
    "Ember",
    "Flamethrower",
    "Mist",
    "Water Gun",
    "Hydro Pump",
    "Surf",
    "Ice Beam",
    "Blizzard",
    "Psybeam",
    "Bubble Beam",
    "Aurora Beam",
    "Hyper Beam",
    "Peck",
    "Drill Peck",
    "Submission",
    "Low Kick",
    "Counter",
    "Seismic Toss",
    "Strength",
    "Absorb",
    "Mega Drain",
    "Leech Seed",
    "Growth",
    "Razor Leaf",
    "Solar Beam",
    "PoisonPowder",
    "Stun Spore",
    "Sleep Powder",
    "Petal Dance",
    "StringShot",
    "Dragon Rage",
    "Fire Spin",
    "ThunderShock",
    "Thunderbolt",
    "Thunder Wave",
    "Thunder",
    "Rock Throw",
    "Earthquake",
    "Fissure",
    "Dig",
    "Toxic",
    "Confusion",
    "Psychic",
    "Hypnosis",
    "Meditate",
    "Agility",
    "Quick Attack",
    "Rage",
    "Teleport",
    "Night Shade",
    "Mimic",
    "Screech",
    "Double Team",
    "Recover",
    "Harden",
    "Minimize",
    "Smokescreen",
    "Confuse Ray",
    "Withdraw",
    "Defense Curl",
    "Barrier",
    "Light Screen",
    "Haze",
    "Reflect",
    "Focus Energy",
    "Bide",
    "Metronome",
    "Mirror Move",
    "SelfDestruct",
    "Egg bomb",
    "Lick",
    "Smog",
    "Sludge",
    "Bone Club",
    "Fire Blast",
    "Waterfall",
    "Clamp",
    "Swift",
    "Skull Bash",
    "Spike Cannon",
    "Constrict",
    "Amnesia",
    "Kinesis",
    "Soft-Boiled",
    "Hi Jump Kick",
    "Glare",
    "Dream Eater",
    "Poison Gas",
    "Barrage",
    "Leech Life",
    "Lovely Kiss",
    "Sky Attack",
    "Transform",
    "Bubble",
    "Dizzy Punch",
    "Spore",
    "Flash",
    "Psywave",
    "Splash",
    "Acid Armor",
    "Crabhammer",
    "Explosion",
    "Fury Swipes",
    "Bonemerang",
    "Rest",
    "Rock Slide",
    "Hyper Fang",
    "Sharpen",
    "Conversion",
    "Tri Attack",
    "Super Fang",
    "Slash",
    "Substitute",
    "Struggle",
    "Fairy Wind",
    "Triple Kick",
    "DrainingKiss",
    "Moonblast",
    "Rage Fist",
    "StrangeSteam",
    "Flame Wheel",
    "Dark Pulse",
    "Night Slash",
    "Play Rough",
    "Burning Mist",
    "Aeroblast",
    "Cotton Spore",
    "Laughing Gas",
    "Nothing",
    "Powder Snow",
    "Miasma",
    "Mach Punch",
    "Scary Face",
    "Feint Attack",
    "Sweet Kiss",
    "Shock Smog",
    "Sludge Bomb",
    "Mud-Slap",
    "Octazooka",
    "Bass Tremor",
    "Zap Cannon",
    "Hyper Voice",
    "Flash Cannon",
    "Iron Defense",
    "Icy Wind",
    "Iron Head",
    "Bone Rush",
    "Air Slash",
    "Outrage",
    "X-Scissor",
    "Giga Drain",
    "Signal Beam",
    "Charm",
    "Rollout",
    "Seed Bomb",
    "Poison Jab",
    "Sharp Point",
    "Spark",
    "3-D Attack",
    "Steel Wing",
    "Cyber Crush",
    "Odd Wave",
    "Nothing",
    "Nothing",
    "Nothing",
    "Nothing",
    "Nothing",
    "Nothing",
    "Nothing",
    "Sacred Fire",
    "Nothing",
    "DynamicPunch",
    "Megahorn",
    "DragonBreath",
    "Nothing",
    "Nothing",
    "Nothing",
    "Nothing",
    "Sweet Scent",
    "Iron Tail",
    "Metal Claw",
    "Nothing",
    "Morning Sun",
    "Synthesis",
    "Moonlight",
    "Nothing",
    "Cross Chop",
    "Twister",
    "Nothing",
    "Nothing",
    "Crunch",
    "Nothing",
    "Nothing",
    "ExtremeSpeed",
    "AncientPower",
    "Shadow Ball",
    "Nothing",
    "Rock Smash",
    "Nothing",
    "Dice Roll",
    "Wood Hammer",
    "Twig Slap",
    "Noise Pulse",
    "Nothing",
    NULL
};

const char *MapNames[]=
{
    "0x00 Gravel Town",
    "0x01 Seashore City",
    "0x02 Jaeru City",
    "0x03 Hayward City",
    "0x04 Merson City",
    "0x05 Castro Valley",
    "0x06 Moraga Town",
    "0x07 Owsauri City",
    "0x08 Eagulou City",
    "0x09 Rijon League Entrance",
    "0x0A Botan City",
    "0x0B ",
    "0x0C Route 53",
    "0x0D Route 52",
    "0x0E Route 59",
    "0x0F Route 64",
    "0x10 Route 57",
    "0x11 Route 58",
    "0x12 Route 60",
    "0x13 Route 54",
    "0x14 Route 63",
    "0x15 Route 55",
    "0x16 Route 62",
    "0x17 Route 61",
    "0x18 Final Dungeon Underground Path",
    "0x19 Final Dungeon Outdoor Path",
    "0x1A Azalea Town",
    "0x1B Route 47-B",
    "0x1C Route 48-B",
    "0x1D Route 49",
    "0x1E Route 66",
    "0x1F Route 56",
    "0x20 UNUSED (Gravel Town copy?)",
    "0x21 Route 67",
    "0x22 Route 65",
    "0x23 Route 51",
    "0x24 Route 50",
    "0x25 ",
    "0x26 ",
    "0x27 ",
    "0x28 ",
    "0x29 ",
    "0x2A ",
    "0x2B ",
    "0x2C ",
    "0x2D Eagulou City Gym",
    "0x2E ",
    "0x2F ",
    "0x30 ",
    "0x31 ",
    "0x32 ",
    "0x33 Castro Forest",
    "0x34 Botan City Cave",
    "0x35 ",
    "0x36 Merson City Gym",
    "0x37 ",
    "0x38 Jaeru City Pokémart",
    "0x39 ",
    "0x3A ",
    "0x3B Merson Cave 1F",
    "0x3C Merson Cave B1F",
    "0x3D Final Dungeon Underground Cave Maze 1F",
    "0x3E ",
    "0x3F Final Dungeon Underground Cave Maze Cave Room",
    "0x40 ",
    "0x41 Owsauri City Gym",
    "0x42 ",
    "0x43 Moraga Town Pokémart",
    "0x44 ",
    "0x45 ",
    "0x46 ",
    "0x47 ",
    "0x48 ",
    "0x49 ",
    "0x4A ",
    "0x4B ",
    "0x4C ",
    "0x4D ",
    "0x4E ",
    "0x4F ",
    "0x50 ",
    "0x51 ",
    "0x52 Final Dungeon Underground Cave Maze B1F",
    "0x53 Power Plant",
    "0x54 ",
    "0x55 Final Dungeon Final Cave",
    "0x56 ",
    "0x57 ",
    "0x58 ",
    "0x59 ",
    "0x5A ",
    "0x5B Castro Valley Pokémart",
    "0x5C Jaeru Gym",
    "0x5D Seneca Caverns B1F",
    "0x5E ",
    "0x5F ",
    "0x60 UNuSED (SSAnne)",
    "0x61 ",
    "0x62 ",
    "0x63 ",
    "0x64 SS Anne Dock",
    "0x65 ",
    "0x66 ",
    "0x67 ",
    "0x68 Final Dungeon Teleport Rooms",
    "0x69 Slowpoke Well 1F",
    "0x6A ",
    "0x6B ",
    "0x6C Eagulou Gym 1F",
    "0x6D ",
    "0x6E ",
    "0x6F International Tunnel 1F",
    "0x70 ",
    "0x71 Lance's Room",
    "0x72 ",
    "0x73 ",
    "0x74 ",
    "0x75 ",
    "0x76 ",
    "0x77 Route 56-Moraga Town City Underpass",
    "0x78 Mura's Room (Rival/Champion)",
    "0x79 Route 52-55 Dock Underpass",
    "0x7A Hayward City Mall 1F",
    "0x7B Hayward City Mall 2F",
    "0x7C Hayward City Mall 3F",
    "0x7D Hayward City Mall 4F",
    "0x7E Hayward City Mall Roof",
    "0x7F Hayward City Mall Elevator",
    "0x80 ",
    "0x81 ",
    "0x82 ",
    "0x83 ",
    "0x84 ",
    "0x85 ",
    "0x86 Moraga Town Gym",
    "0x87 Owsauri City Game Corner",
    "0x88 ",
    "0x89 ",
    "0x8A ",
    "0x8B ",
    "0x8C ",
    "0x8D ",
    "0x8E Haunted Forest Area 1",
    "0x8F Haunted Forest Area 2",
    "0x90 Haunted Forest Area 3",
    "0x91 Haunted Forest Area 4",
    "0x92 Haunted Forest Area 5",
    "0x93 Haunted Forest Area 6",
    "0x94 Haunted Forest Area 7",
    "0x95 ",
    "0x96 Merson City Pokémart",
    "0x97 ",
    "0x98 Owsauri City Pokémart",
    "0x99 ",
    "0x9A ",
    "0x9B ",
    "0x9C Eagulou Park Gate",
    "0x9D Castro Valley Gym",
    "0x9E ",
    "0x9F Silk Tunnel B1F",
    "0xA0 Silk Tunnel B2F",
    "0xA1 Mt. Boulder 1F",
    "0xA2 Mt. Boulder B1F",
    "0xA3 ",
    "0xA4 ",
    "0xA5 Koolboyman Mansion 1F",
    "0xA6 Normal Type Gym",
    "0xA7 ",
    "0xA8 ",
    "0xA9 ",
    "0xAA ",
    "0xAB ",
    "0xAC Eagulou City Pokémart",
    "0xAD ",
    "0xAE Rijon League",
    "0xAF ",
    "0xB0 UNUSED (Pokédoll House 1F)",
    "0xB1 ",
    "0xB2 Seashore City Gym",
    "0xB3 ",
    "0xB4 Botan City Pokémart",
    "0xB5 ",
    "0xB6 ",
    "0xB7 Slowpoke Well B1F",
    "0xB8 ",
    "0xB9 ",
    "0xBA ",
    "0xBB ",
    "0xBC ",
    "0xBD ",
    "0xBE ",
    "0xBF ",
    "0xC0 Silk Tunnel 1F",
    "0xC1 ",
    "0xC2 30 Years Cave",
    "0xC3 ",
    "0xC4 ",
    "0xC5 Rijon Tunnel 1F",
    "0xC6 Eagulou Park Secret Cave B1",
    "0xC7 Final Duneon Main Building 1F",
    "0xC8 ",
    "0xC9 Final Dungeon Main Building B1F",
    "0xCA Final Dungeon Final Island",
    "0xCB ",
    "0xCC ",
    "0xCD ",
    "0xCE ",
    "0xCF ",
    "0xD0 ",
    "0xD1 Sylph Warehouse B1F",
    "0xD2 International Tunnel B1F",
    "0xD3 ",
    "0xD4 ",
    "0xD5 Seneca Caverns 1F",
    "0xD6 Koolboyman Mansion 2F",
    "0xD7 Koolboyman Mansion 3F",
    "0xD8 Koolboyman Mansion B1F",
    "0xD9 Eagulou Park Area 3",
    "0xDA Eagulou Park Area 2",
    "0xDB Seneca Caverns B2F",
    "0xDC Eagulou Park Area 1",
    "0xDD ",
    "0xDE ",
    "0xDF ",
    "0xE0 ",
    "0xE1 ",
    "0xE2 Azalea Town-Illex Forest Gate",
    "0xE3 Eagulou Park Secret Cave B2",
    "0xE4 Illex Forest",
    "0xE5 ",
    "0xE6 ",
    "0xE7 ",
    "0xE8 Silk Tunnel B3F",
    "0xE9 Final Dungeon Final Island *Pokécenter*",
    "0xEA Route 34 (Johto)",
    "0xEB ",
    "0xEC ",
    "0xED ",
    "0xEE ",
    "0xEF ",
    "0xF0 ",
    "0xF1 ",
    "0xF2 ",
    "0xF3 Merson Cave Healing Room",
    "0xF4 ",
    "0xF5 Redd's Room",
    "0xF6 Jared's Room",
    "0xF7 Agatha's Room", //This is the last map, there's only 248 maps, this is ID 247
    "0xF8",
    "0xF9",
    "0xFA",
    "0xFB",
    "0xFC",
    "0xFD",
    "0xFE",
    "0xFF",
    NULL

};

//A little hacky, the first element shouldn't be there, but works like this right now to work with ...
int data2dex[] =
{
    0,//This shouldn't be there
    112,
    115,
    32,
    35,
    21,
    100,
    34,
    80,
    2,
    103,
    108,
    102,
    88,
    94,
    29,
    31,
    104,
    111,
    131,
    59,
    151,
    130,
    90,
    72,
    92,
    123,
    120,
    9,
    127,
    114,
    152,
    153,
    58,
    95,
    22,
    16,
    79,
    64,
    75,
    113,
    67,
    122,
    106,
    107,
    24,
    47,
    54,
    96,
    76,
    223,
    126,
    183,
    125,
    82,
    109,
    155,
    56,
    86,
    50,
    128,
    156,
    157,
    158,
    83,
    48,
    149,
    159,
    160,
    161,
    84,
    60,
    124,
    146,
    144,
    145,
    132,
    52,
    98,
    162,
    163,
    164,
    37,
    38,
    25,
    26,
    224,
    194,
    147,
    148,
    140,
    141,
    116,
    117,
    166,
    167,
    27,
    28,
    138,
    139,
    39,
    40,
    133,
    136,
    135,
    134,
    66,
    41,
    23,
    46,
    61,
    62,
    13,
    14,
    15,
    218,
    85,
    57,
    51,
    49,
    87,
    168,
    169,
    10,
    11,
    12,
    68,
    170,
    55,
    97,
    42,
    150,
    143,
    129,
    171,
    196,
    89,
    220,
    99,
    91,
    196,
    101,
    36,
    110,
    53,
    105,
    196,
    93,
    63,
    65,
    17,
    18,
    121,
    1,
    3,
    73,
    173,
    118,
    119,
    174,
    175,
    176,
    219,
    77,
    78,
    19,
    20,
    33,
    30,
    74,
    137,
    142,
    192,
    81,
    178,
    179,
    4,
    7,
    5,
    8,
    6,
    180,
    0,
    198,
    182,
    43,
    44,
    45,
    69,
    70,
    71,
    185,
    186,
    189,
    190,
    187,
    188,
    200,
    201,
    133,
    133,
    133,
    184,
    216,
    177,
    221,
    222,
    204,
    217,
    214,
    215,
    209,
    213,
    207,
    208,
    181,
    199,
    202,
    203,
    205,
    206,
    172,
    165,
    197,
    212,
    191,
    211,
    193,
    210,
    195,
    154,
    225,
    226,
    227,
    228, //234 index
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    252, //252 index
    255,
    255,
    255,
    255 //256
};

const char *SpeciesName[]=
{
    "000 No Pokemon",
    "Rhydon",
    "Kangaskhan",
    "NidoranM",
    "Clefairy",
    "Spearow",
    "Voltorb",
    "Nidoking",
    "Slowbro",
    "Ivysaur",
    "Exeggutor",
    "Lickitung",
    "Exeggcute",
    "Grimer",
    "Gengar",
    "NidoranF",
    "Nidoqueen",
    "Cubone",
    "Rhyhorn",
    "Lapras",
    "Arcanine",
    "Mew",
    "Gyarados",
    "Shellder",
    "Tentacool",
    "Gastly",
    "Scyther",
    "Staryu",
    "Blastoise",
    "Pinsir",
    "Tangela",
    "Chikorita",
    "Bayleef",
    "Growlithe",
    "Onix",
    "Fearow",
    "Pidgey",
    "Slowpoke",
    "Kadabra",
    "Graveler",
    "Chansey",
    "Machoke",
    "Mr. Mime",
    "Hitmonlee",
    "Hitmonchan",
    "Arbok",
    "Parasect",
    "Psyduck",
    "Drowzee",
    "Golem",
    "Cranidos",
    "Magmar",
    "Pupitar",
    "Electabuzz",
    "Magneton",
    "Koffing",
    "Cyndaquil",
    "Mankey",
    "Seel",
    "Diglett",
    "Tauros",
    "Quilava",
    "Typhlosion",
    "Totodile",
    "Farfetch'd",
    "Venonat",
    "Dragonite",
    "Croconaw",
    "Feraligatr",
    "Houndour",
    "Doduo",
    "Poliwag",
    "Jynx",
    "Moltres",
    "Articuno",
    "Zapdos",
    "Ditto",
    "Meowth",
    "Krabby",
    "Houndoom",
    "Heracross",
    "Yanma",
    "Vulpix",
    "Ninetales",
    "Pikachu",
    "Raichu",
    "Rampardos",
    "Sneasel",
    "Dratini",
    "Dragonair",
    "Kabuto",
    "Kabutops",
    "Horsea",
    "Seadra",
    "Spinarak",
    "Ariados",
    "Sandshrew",
    "Sandslash",
    "Omanyte",
    "Omastar",
    "Jigglypuff",
    "Wigglytuff",
    "Eevee (Espeon)",
    "Flareon",
    "Jolteon",
    "Vaporeon",
    "Machop",
    "Zubat",
    "Ekans",
    "Paras",
    "Poliwhirl",
    "Poliwrath",
    "Weedle",
    "Kakuna",
    "Beedrill",
    "Raikou",
    "Dodrio",
    "Primeape",
    "Dugtrio",
    "Venomoth",
    "Dewgong",
    "Chinchou",
    "Lanturn",
    "Caterpie",
    "Metapod",
    "Butterfree",
    "Machamp",
    "Swinub",
    "Golduck",
    "Hypno",
    "Golbat",
    "Mewtwo",
    "Snorlax",
    "Magikarp",
    "Piloswine",
    "Tyrogue (Hitmonchan)",
    "Muk",
    "Suicune",
    "Kingler",
    "Cloyster",
    "Tyrogue (Hitmonlee)",
    "Electrode",
    "Clefable",
    "Weezing",
    "Persian",
    "Marowak",
    "Tyrogue (Hitmontop)",
    "Haunter",
    "Abra",
    "Alakazam",
    "Pidgeotto",
    "Pidgeot",
    "Starmie",
    "Bulbasaur",
    "Venusaur",
    "Tentacruel",
    "Natu",
    "Goldeen",
    "Seaking",
    "Xatu",
    "Mareep",
    "Flaaffy",
    "Entei",
    "Ponyta",
    "Rapidash",
    "Rattata",
    "Raticate",
    "Nidorino",
    "Nidorina",
    "Geodude",
    "Porygon",
    "Aerodactyl",
    "Gligar",
    "Magnemite",
    "Marill",
    "Azumarill",
    "Charmander",
    "Squirtle",
    "Charmeleon",
    "Wartortle",
    "Charizard",
    "Murkrow",
    "Ghost (MissingNo.)",
    "Misdreavus",
    "Larvitar",
    "Oddish",
    "Gloom",
    "Vileplume",
    "Bellsprout",
    "Weepinbell",
    "Victreebel",
    "Phanpy",
    "Donphan",
    "Togepi",
    "Togetic",
    "Wooper",
    "Quagsire",
    "Espeon",
    "Umbreon",
    "Eevee (Umbreon)",
    "Eevee (Leafeon)",
    "Eevee (Glaceon)",
    "Tyranitar",
    "Crobat",
    "Ampharos",
    "Lugia",
    "Ho-Oh",
    "Magnezone",
    "Politoed",
    "Rhyperior",
    "Blissey",
    "Tangrowth",
    "Kingdra",
    "Porygon2",
    "Porygon-Z",
    "Honchkrow",
    "Mismagius",
    "Leafeon",
    "Glaceon",
    "Electivire",
    "Magmortar",
    "Mamoswine",
    "Yanmega",
    "Hitmontop",
    "Slowking",
    "Togekiss",
    "Steelix",
    "Gliscor",
    "Scizor",
    "Weavile",
    "Meganium",
    "Sylveon",
    "Annihilape",
    "G.Weezing",
    "Lickilikky",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "Phancero",
    "?????",
    "?????",
    "?????",
    NULL
};

const char *ItemName[]=
{
    "00GLITCH",
    "Master Ball",
    "Ultra ball",
    "Great ball",
    "Pokeball",
    "Town Map",
    "Bycicle",
    "07GLITCH",
    "Park Ball",
    "08GLITCH",
    "Moon Stone",
    "Antidote",
    "Burn Heal",
    "Ice Heal",
    "Awakening",
    "Paraliz Heal",
    "Full Restore",
    "Max potion",
    "Hyper potion",
    "Super potion",
    "Potion",
    "09GLITCH",
    "10GLITCH",
    "Red Orb",
    "Blue Orb",
    "Green Orb",
    "Dusk Stone",
    "Up-Grade",
    "Shiny Stone",
    "Escape Rope",
    "Repel",
    "Skull Fossil",
    "Fire Stone",
    "Thunder Stone",
    "Water Stone",
    "HP Up",
    "Protein",
    "Iron",
    "Carbos",
    "Calcium",
    "Rare Candy",
    "Dome Fossil",
    "Helix Fossil",
    "Mist Stone",
    "Dubious Disk",
    "Bike Voucher",
    "X Accuracy",
    "Leaf Stone",
    "Card Key",
    "Nugget",
    "PP Up",
    "Poké Doll",
    "Full Heal",
    "Revive",
    "Max Revive",
    "Guard Spec.",
    "Super Repel",
    "Max Repel",
    "Dire Hit",
    "GLITCH (COIN)",
    "Beer Keg",
    "Soda",
    "Lemonade",
    "S.S.Ticket",
    "Red Amulet",
    "X Attack",
    "X Defend",
    "X Speed",
    "X Special",
    "Coin Case",
    "Tim's Pizza",
    "ItemFInder",
    "Virus Scan",
    "Poké Flute",
    "GLITCH",
    "Exp.All",
    "Old Rod",
    "Good Rod",
    "Super Rod",
    "PP UP",
    "Ether",
    "Max Ether",
    "Elixer",
    "Max Elixer",
    "Metal Coat",
    "Magmarizer",
    "Electrizer",
    "Trade Stone",
    "Protector",
    "Razor Fang",
    "Razor Claw",
    "King's Rock",
    "Dragon Scale",
    "Pearl",
    "Big Pearl",
    "Stardust",
    "Star Piece",
    "TinyMushroom",
    "Mushroom",
    "Gold Leaf",
    "Sapphire Egg",
    "Brick Piece/Ice Stone",
    "Rare Bone",
    "CoronetStone",
    "Ruby Egg",
    "Gold Egg",
    "Crystal Egg",
    "Emeral Egg",
    "Prism Key",
    "Silver Egg",
    "Magic Wand ",
    "1F",
    "2F",
    "3F",
    "4F",
    "5F",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "NODATA",
    "HM01",
    "HM02",
    "HM03",
    "HM04",
    "HM05",
    "TM01",
    "TM02",
    "TM03",
    "TM04",
    "TM05",
    "TM06",
    "TM07",
    "TM08",
    "TM09",
    "TM10",
    "TM11",
    "TM12",
    "TM13",
    "TM14",
    "TM15",
    "TM16",
    "TM17",
    "TM18",
    "TM19",
    "TM20",
    "TM21",
    "TM22",
    "TM23",
    "TM24",
    "TM25",
    "TM26",
    "TM27",
    "TM28",
    "TM29",
    "TM30",
    "TM31",
    "TM32",
    "TM33",
    "TM34",
    "TM35",
    "TM36",
    "TM37",
    "TM38",
    "TM39",
    "TM40",
    "TM41",
    "TM42",
    "TM43",
    "TM44",
    "TM45",
    "TM46",
    "TM47",
    "TM48",
    "TM49",
    "TM50",
    "TM51",
    "TM52",
    "TM53",
    "TM54",
    "TM55",
    NULL
};

const char *DexOrderNames[]=
{
    "NOMON",
    "Bulbasaur",
    "Ivysaur",
    "Venusaur",
    "Charmander",
    "Charmeleon",
    "Charizard",
    "Squirtle",
    "Wartortle",
    "Blastoise",
    "Caterpie",
    "Metapod",
    "Butterfree",
    "Weedle",
    "Kakuna",
    "Beedrill",
    "Pidgey",
    "Pidgeotto",
    "Pidgeot",
    "Rattata",
    "Raticate",
    "Spearow",
    "Fearow",
    "Ekans",
    "Arbok",
    "Pikachu",
    "Raichu",
    "Sandshrew",
    "Sandslash",
    "NidoranF",
    "Nidorina",
    "Nidoqueen",
    "NidoranM",
    "Nidorino",
    "Nidoking",
    "Clefairy",
    "Clefable",
    "Vulpix",
    "Ninetales",
    "Jigglypuff",
    "Wigglytuff",
    "Zubat",
    "Golbat",
    "Oddish",
    "Gloom",
    "Vileplume",
    "Paras",
    "Parasect",
    "Venonat",
    "Venomoth",
    "Diglett",
    "Dugtrio",
    "Meowth",
    "Persian",
    "Psyduck",
    "Golduck",
    "Mankey",
    "Primeape",
    "Growlithe",
    "Arcanine",
    "Poliwag",
    "Poliwhirl",
    "Poliwrath",
    "Abra",
    "Kadabra",
    "Alakazam",
    "Machop",
    "Machoke",
    "Machamp",
    "Bellsprout",
    "Weepinbell",
    "Victreebel",
    "Tentacool",
    "Tentacruel",
    "Geodude",
    "Graveler",
    "Golem",
    "Ponyta",
    "Rapidash",
    "Slowpoke",
    "Slowbro",
    "Magnemite",
    "Magneton",
    "Farfetch'd",
    "Doduo",
    "Dodrio",
    "Seel",
    "Dewgong",
    "Grimer",
    "Muk",
    "Shellder",
    "Cloyster",
    "Gastly",
    "Haunter",
    "Gengar",
    "Onix",
    "Drowzee",
    "Hypno",
    "Krabby",
    "Kingler",
    "Voltorb",
    "Electrode",
    "Exeggcute",
    "Exeggutor",
    "Cubone",
    "Marowak",
    "Hitmonlee",
    "Hitmonchan",
    "Lickitung",
    "Koffing",
    "Weezing",
    "Rhyhorn",
    "Rhydon",
    "Chansey",
    "Tangela",
    "Kangaskhan",
    "Horsea",
    "Seadra",
    "Goldeen",
    "Seaking",
    "Staryu",
    "Starmie",
    "Mr. Mime",
    "Scyther",
    "Jynx",
    "Electabuzz",
    "Magmar",
    "Pinsir",
    "Tauros",
    "Magikarp",
    "Gyarados",
    "Lapras",
    "Ditto",
    "Eevee",
    "Vaporeon",
    "Jolteon",
    "Flareon",
    "Porygon",
    "Omanyte",
    "Omastar",
    "Kabuto",
    "Kabutops",
    "Aerodactyl",
    "Snorlax",
    "Articuno",
    "Zapdos",
    "Moltres",
    "Dratini",
    "Dragonair",
    "Dragonite",
    "Mewtwo",
    "Mew",
    "Chikorita",
    "Bayleef",
    "Meganium",
    "Cyndaquil",
    "Quilava",
    "Typhlosion",
    "Totodile",
    "Croconaw",
    "Feraligatr",
    "Houndour",
    "Houndoom",
    "Heracross",
    "Yanma",
    "Yanmega",
    "Spinarak",
    "Ariados",
    "Chinchou",
    "Lanturn",
    "Swinub",
    "Piloswine",
    "Mamoswine",
    "Natu",
    "Xatu",
    "Mareep",
    "Flaaffy",
    "Ampharos",
    "Marill",
    "Azumarill",
    "Murkrow",
    "Honchkrow",
    "Larvitar",
    "Pupitar",
    "Tyranitar",
    "Phanpy",
    "Donphan",
    "Wooper",
    "Quagsire",
    "Togepi",
    "Togetic",
    "Togekiss",
    "Gligar",
    "Gliscor",
    "Sneasel",
    "Weavile",
    "Tyrogue",
    "Hitmontop",
    "Misdreavus",
    "Mismagius",
    "Espeon",
    "Umbreon",
    "Leafeon",
    "Glaceon",
    "Magnezone",
    "Electivire",
    "Magmortar",
    "Porygon2",
    "Porygon-Z",
    "Tangrowth",
    "Scizor",
    "Steelix",
    "Slowking",
    "Kingdra",
    "Rhyperior",
    "Blissey",
    "Crobat",
    "Politoed",
    "Raikou",
    "Entei",
    "Suicune",
    "Lugia",
    "Ho-Oh",
    "Cranidos",
    "Rampardos",
    "Sylveon",
    "Annihilape",
    "G.Weezing",
    "Lickilicky",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "?????",
    "Phancero",
    "?????",
    "?????",
    "?????",
    NULL
};

const char *GrowthRates[]=
{
    "Medium Fast",
    "Slightly Fast",
    "Slightly Slow",
    "Medium Slow",
    "Fast",
    "Slow",
    NULL
};

const char *Types[]=
{
	"NORMAL",       //$00
	"FIGHTING",       //$01
	"FLYING",         //$02
	"POISON",         //$03
	"GROUND",         //$04
	"ROCK",           //$05
	"BIRD",           //$06
	"BUG",            //$07
	"GHOST",          //$08
    "STEEL",    //&09
    "0A",
    "0B",
    "0C",
    "WIND",
    "SOUND", //$0E
    "TRI",
    "10",
    "11",
    "12",
    "13",
    "FIRE",         //$14
	"WATER",        //$15
	"GRASS",       //$16
	"ELECTRIC",     //$17
	"PSYCHIC", //$18
	"ICE",          //$19
	"DRAGON",       //$1A
    "DARK", //$1B
    "WOOD", //$1C
    "GAS", //1D
    "ABNORMAL", //$1E
    "FAIRY", //$1F
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    NULL
};

const char *TypesTable[]=
{
	"NORMAL  ",       //$00
	"FIGHTING",       //$01
	"FLYING  ",         //$02
	"POISON  ",         //$03
	"GROUND  ",         //$04
	"ROCK    ",           //$05
	"BIRD    ",           //$06
	"BUG     ",            //$07
	"GHOST   ",          //$08
    "STEEL   ",    //&09
    "0A",
    "0B",
    "0C",
    "WIND    ",
    "SOUND   ", //$0E
    "TRI     ",
    "10",
    "11",
    "12",
    "13",
    "FIRE    ",         //$14
	"WATER   ",        //$15
	"GRASS   ",       //$16
	"ELECTR  ",     //$17
	"PSYCHIC ", //$18
	"ICE     ",          //$19
	"DRAGON  ",       //$1A
    "DARK    ", //$1B
    "WOOD    ", //$1C
    "GAS     ", //1D
    "ABNORMAL", //$1E
    "FAIRY   ", //$1F
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    NULL
};

const int TypesMatchesIds[]=
{
    0x00, //Normal
    0x01, //Fighting
    0x02, //Flying
    0x03, //Poison
    0x04, //Ground
    0x05, //Rock
    0x07, //Bug
    0x08, //Ghost
    0x09, //Steel
    0x0D, //Wind
    0x0E, //Sound
    0x0F, //Tri
    0x14, //Fire
    0x15, //Water
    0x16, //Grass
    0x17, //Electric
    0x18, //Psyichic
    0x19, //Ice
    0x1A, //Dragon
    0x1B, //Dark
    0x1C, //Wood
    0x1D, //Gas
    0x1E, //Abnormal
    0x1F //Fairy
};

const char* TypesMatchesNames[]=
{
	"NORMAL  ",       //$00
	"FIGHTING",       //$01
	"FLYING  ",         //$02
	"POISON  ",         //$03
	"GROUND  ",         //$04
	"ROCK    ",           //$05
	"BUG     ",            //$07
	"GHOST   ",          //$08
    "STEEL   ",    //&09
    "WIND    ", //$0D
    "SOUND   ", //$0E
    "TRI     ", //$0F
    "FIRE    ",         //$14
	"WATER   ",        //$15
	"GRASS   ",       //$16
	"ELECTR  ",     //$17
	"PSYCHIC ", //$18
	"ICE     ",          //$19
	"DRAGON  ",       //$1A
    "DARK    ", //$1B
    "WOOD    ", //$1C
    "GAS     ", //1D
    "ABNORMAL", //$1E
    "FAIRY   ", //$1F
    NULL
};

const char *TM_HM[]=
{
    "TM01: Dynamicpunch",
    "TM02: Razor Wind",
    "TM03: Swords Dance",
    "TM04: Aeroblast/Air Slash",
    "TM05: Triple Kick/Dizzy Punch",
    "TM06: Toxic",
    "TM07: Horn Drill",
    "TM08: Body Slam",
    "TM09: Take Down",
    "TM10: Double-Edge",
    "TM11: Bubblebeam/Signal Beam",
    "TM12: Octazooka",
    "TM13: Ice Beam",
    "TM14: Blizzard",
    "TM15: Hyper Beam",
    "TM16: Pay Day",
    "TM17: Submission",
    "TM18: Counter",
    "TM19: Seismic Toss",
    "TM20: Rage/Steel Wing",
    "TM21: Giga Drain",
    "TM22: Solarbeam",
    "TM23: Dragonbreath",
    "TM24: Thunderbolt",
    "TM25: Thunder",
    "TM26: Earthquake",
    "TM27: Fissure",
    "TM28: Dig",
    "TM29: Psychic",
    "TM30: Shadow Ball",
    "TM31: Mimic",
    "TM32: Double Team",
    "TM33: Reflect",
    "TM34: Bide/Burning Mist",
    "TM35: Metronome",
    "TM36: Sludge Bomb",
    "TM37: Megahorn",
    "TM38: Flamethower",
    "TM39: Swift",
    "TM40: Skull Bash",
    "TM41: Wood Hammer/Seed Bomb",
    "TM42: Dream Eater",
    "TM43: Sky Attack",
    "TM44: Rest",
    "TM45: Thunder Wave",
    "TM46: Noise Pulse",
    "TM47: Explosion",
    "TM48: Rock Slide",
    "TM49: Tri Attack",
    "TM50: Substitute",
    "HM01: Cut",
    "HM02: Fly",
    "HM03: Surf",
    "HM04: Strength",
    "HM05: Flash",
    NULL
};

const char *EVO_TYPE[]=
{
    "NONE    ",
    "EV_LEVEL",
	"EV_ITEM ",
	"EV_TRADE",
	"EV_GEO",
	"EV_ATK",
	"EV_DEF",
	"EV_ATKDEF",
	NULL
};

const char *TRAINER_CLASS[]=
{
    "Nobody",
    "Youngster",
    "Bug Catcher",
    "Lass",
    "Sailor",
    "Jr Trainer M",
    "Jr Trainer F",
    "Pokemaniac",
    "Super Nerd",
    "Hiker",
    "Biker",
    "Burglar",
    "Engineer",
    "PaletteBlack",
    "Fisher",
    "Swimmer",
    "Cue Ball",
    "Gambler",
    "Beauty",
    "Psychic",
    "Rocker",
    "Juggler",
    "Tamer",
    "Bird Keeper",
    "Blackbelt",
    "Rival1",
    "Palette Red",
    "Bugsy",
    "Scientist",
    "Giovanni",
    "Rocket",
    "Cooltrainer M",
    "Cooltrainer F",
    "Jared",
    "Karpman",
    "Lily",
    "Sparky",
    "Lois",
    "Koji",
    "Joe",
    "Sheral",
    "Gentleman",
    "Rival2",
    "Rival3",
    "Redd",
    "Channeler",
    "Agatha",
    "Drake",
    NULL
};

const uint16_t ItemAIPointers[19]=
{
    0x65e9,
    0x65ef,
    0x65f5,
    0x65fb,
    0x6601,
    0x6614,
    0x661c,
    0x6622,
    0x6628,
    0x6634,
    0x663a,
    0x6640,
    0x664c,
    0x6658,
    0x6664,
    0x6670,
    0x6676,
    0x6687,
    0x6693
};

const char *ItemAINames[]=
{
    "JugglerAI",
    "BlackbeltAI",
    "GiovanniAI",
    "CooltrainerMAI",
    "CooltrainerFAI",
    "BrockAI",
    "MistyAI",
    "LtSurgeAI",
    "ErikaAI",
    "KogaAI",
    "BlaineAI",
    "SabrinaAI",
    "Rival2AI",
    "Rival3AI",
    "LoreleiAI",
    "BrunoAI",
    "AgathaAI",
    "LanceAI",
    "GenericAI",
    NULL
};

const char *ItemAIItems[]=
{
    "Switch Mon 25%",
    "Use X Attack 13%",
    "Use Guard Spec 25%",
    "Use X Attack 25%",
    "Use Hyper Potion",
    "Use Full Heal",
    "Use X Defense 25%",
    "Use X Speed 25%",
    "Use Super Potion",
    "Use X Attack 25%",
    "Use Super Potion 25%",
    "Use Hyper Potion",
    "Use Potion",
    "Use Full Restore",
    "Use Super Potion",
    "Use X Defense 25%",
    "Use Super Potion / Switch Mon 8% chance",
    "Use Super Potion",
    "Nothing",
    NULL
};

